using System;
using Waher.Networking.HTTP.Mcp.Model.Attributes;

namespace Waher.Mcp.Identity.UserInput
{
	internal enum Gender
	{
		/// <summary>
		/// Male
		/// </summary>
		M,

		/// <summary>
		/// Female
		/// </summary>
		F
	}

	/// <summary>
	/// Class containing user input parameters for a personal identity application
	/// </summary>
	internal class PersonalInformationInput
	{
		/// <summary>
		/// First name of the user.
		/// </summary>
		[McpStringParameter("First Name", "First name of the user.", 1, 128)]
		public string FirstName = string.Empty;

		/// <summary>
		/// Middle names of the user.
		/// </summary>
		[McpStringParameter("Middle Names", "Middle names of the user.", 0, 128)]
		public string? MiddleNames = null;

		/// <summary>
		/// Last names of the user.
		/// </summary>
		[McpStringParameter("Last Names", "Last names of the user.", 1, 128)]
		public string LastNames = string.Empty;

		/// <summary>
		/// Personal number of the user. Must conform to the personal numbering scheme 
		/// defined in the country of residence.
		/// </summary>
		[McpStringParameter("Personal Number", "Personal number of the user. Must " +
			"conform to the personal numbering scheme defined in the country of " +
			"residence.",
			1, 128)]
		public string PersonalNumber = string.Empty;

		/// <summary>
		/// Address where the user is resident.
		/// </summary>
		[McpStringParameter("Address", "Address where the user is resident.", 1, 128)]
		public string Address = string.Empty;

		/// <summary>
		/// Second Address line where the user is resident.
		/// </summary>
		[McpStringParameter("Address 2nd line", "Second Address line where the user is resident.", 0, 128)]
		public string? Address2 = null;

		/// <summary>
		/// Zip or postal code where the user is resident.
		/// </summary>
		[McpStringParameter("Zip", "Zip or postal code where the user is resident.", 1, 128)]
		public string Zip = string.Empty;

		/// <summary>
		/// Area where the user is resident.
		/// </summary>
		[McpStringParameter("Area", "Area where the user is resident.", 0, 128)]
		public string? Area = null;

		/// <summary>
		/// City where the user is resident.
		/// </summary>
		[McpStringParameter("City", "City where the user is resident.", 1, 128)]
		public string City = string.Empty;

		/// <summary>
		/// Region where the user is resident.
		/// </summary>
		[McpStringParameter("Region", "Region where the user is resident.", 0, 128)]
		public string? Region = null;

		/// <summary>
		/// Country where the user is resident. Must conform to ISO 3166.
		/// </summary>
		[McpParameter("Country", "Country where the user is resident.")]
		[McpEnumValue(Iso3166CountryCode.AF, "AFGHANISTAN")]
		[McpEnumValue(Iso3166CountryCode.AX, "ÅLAND ISLANDS")]
		[McpEnumValue(Iso3166CountryCode.AL, "ALBANIA")]
		[McpEnumValue(Iso3166CountryCode.DZ, "ALGERIA")]
		[McpEnumValue(Iso3166CountryCode.AS, "AMERICAN SAMOA")]
		[McpEnumValue(Iso3166CountryCode.AD, "ANDORRA")]
		[McpEnumValue(Iso3166CountryCode.AO, "ANGOLA")]
		[McpEnumValue(Iso3166CountryCode.AI, "ANGUILLA")]
		[McpEnumValue(Iso3166CountryCode.AQ, "ANTARCTICA")]
		[McpEnumValue(Iso3166CountryCode.AG, "ANTIGUA AND BARBUDA")]
		[McpEnumValue(Iso3166CountryCode.AR, "ARGENTINA")]
		[McpEnumValue(Iso3166CountryCode.AM, "ARMENIA")]
		[McpEnumValue(Iso3166CountryCode.AW, "ARUBA")]
		[McpEnumValue(Iso3166CountryCode.AU, "AUSTRALIA")]
		[McpEnumValue(Iso3166CountryCode.AT, "AUSTRIA")]
		[McpEnumValue(Iso3166CountryCode.AZ, "AZERBAIJAN")]
		[McpEnumValue(Iso3166CountryCode.BS, "BAHAMAS")]
		[McpEnumValue(Iso3166CountryCode.BH, "BAHRAIN")]
		[McpEnumValue(Iso3166CountryCode.BD, "BANGLADESH")]
		[McpEnumValue(Iso3166CountryCode.BB, "BARBADOS")]
		[McpEnumValue(Iso3166CountryCode.BY, "BELARUS")]
		[McpEnumValue(Iso3166CountryCode.BE, "BELGIUM")]
		[McpEnumValue(Iso3166CountryCode.BZ, "BELIZE")]
		[McpEnumValue(Iso3166CountryCode.BJ, "BENIN")]
		[McpEnumValue(Iso3166CountryCode.BM, "BERMUDA")]
		[McpEnumValue(Iso3166CountryCode.BT, "BHUTAN")]
		[McpEnumValue(Iso3166CountryCode.BO, "BOLIVIA")]
		[McpEnumValue(Iso3166CountryCode.BA, "BOSNIA AND HERZEGOVINA")]
		[McpEnumValue(Iso3166CountryCode.BW, "BOTSWANA")]
		[McpEnumValue(Iso3166CountryCode.BV, "BOUVET ISLAND")]
		[McpEnumValue(Iso3166CountryCode.BR, "BRAZIL")]
		[McpEnumValue(Iso3166CountryCode.IO, "BRITISH INDIAN OCEAN TERRITORY")]
		[McpEnumValue(Iso3166CountryCode.BN, "BRUNEI DARUSSALAM")]
		[McpEnumValue(Iso3166CountryCode.BG, "BULGARIA")]
		[McpEnumValue(Iso3166CountryCode.BF, "BURKINA FASO")]
		[McpEnumValue(Iso3166CountryCode.BI, "BURUNDI")]
		[McpEnumValue(Iso3166CountryCode.KH, "CAMBODIA")]
		[McpEnumValue(Iso3166CountryCode.CM, "CAMEROON")]
		[McpEnumValue(Iso3166CountryCode.CA, "CANADA")]
		[McpEnumValue(Iso3166CountryCode.CV, "CAPE VERDE")]
		[McpEnumValue(Iso3166CountryCode.KY, "CAYMAN ISLANDS")]
		[McpEnumValue(Iso3166CountryCode.CF, "CENTRAL AFRICAN REPUBLIC")]
		[McpEnumValue(Iso3166CountryCode.TD, "CHAD")]
		[McpEnumValue(Iso3166CountryCode.CL, "CHILE")]
		[McpEnumValue(Iso3166CountryCode.CN, "CHINA")]
		[McpEnumValue(Iso3166CountryCode.CX, "CHRISTMAS ISLAND")]
		[McpEnumValue(Iso3166CountryCode.CC, "COCOS (KEELING) ISLANDS")]
		[McpEnumValue(Iso3166CountryCode.CO, "COLOMBIA")]
		[McpEnumValue(Iso3166CountryCode.KM, "COMOROS")]
		[McpEnumValue(Iso3166CountryCode.CG, "CONGO")]
		[McpEnumValue(Iso3166CountryCode.CD, "CONGO, THE DEMOCRATIC REPUBLIC OF THE")]
		[McpEnumValue(Iso3166CountryCode.CK, "COOK ISLANDS")]
		[McpEnumValue(Iso3166CountryCode.CR, "COSTA RICA")]
		[McpEnumValue(Iso3166CountryCode.CI, "COTE D'IVOIRE")]
		[McpEnumValue(Iso3166CountryCode.HR, "CROATIA")]
		[McpEnumValue(Iso3166CountryCode.CU, "CUBA")]
		[McpEnumValue(Iso3166CountryCode.CY, "CYPRUS")]
		[McpEnumValue(Iso3166CountryCode.CZ, "CZECH REPUBLIC")]
		[McpEnumValue(Iso3166CountryCode.DK, "DENMARK")]
		[McpEnumValue(Iso3166CountryCode.DJ, "DJIBOUTI")]
		[McpEnumValue(Iso3166CountryCode.DM, "DOMINICA")]
		[McpEnumValue(Iso3166CountryCode.DO, "DOMINICAN REPUBLIC")]
		[McpEnumValue(Iso3166CountryCode.EC, "ECUADOR")]
		[McpEnumValue(Iso3166CountryCode.EG, "EGYPT")]
		[McpEnumValue(Iso3166CountryCode.SV, "EL SALVADOR")]
		[McpEnumValue(Iso3166CountryCode.GQ, "EQUATORIAL GUINEA")]
		[McpEnumValue(Iso3166CountryCode.ER, "ERITREA")]
		[McpEnumValue(Iso3166CountryCode.EE, "ESTONIA")]
		[McpEnumValue(Iso3166CountryCode.ET, "ETHIOPIA")]
		[McpEnumValue(Iso3166CountryCode.FK, "FALKLAND ISLANDS (MALVINAS)")]
		[McpEnumValue(Iso3166CountryCode.FO, "FAROE ISLANDS")]
		[McpEnumValue(Iso3166CountryCode.FJ, "FIJI")]
		[McpEnumValue(Iso3166CountryCode.FI, "FINLAND")]
		[McpEnumValue(Iso3166CountryCode.FR, "FRANCE")]
		[McpEnumValue(Iso3166CountryCode.GF, "FRENCH GUIANA")]
		[McpEnumValue(Iso3166CountryCode.PF, "FRENCH POLYNESIA")]
		[McpEnumValue(Iso3166CountryCode.TF, "FRENCH SOUTHERN TERRITORIES")]
		[McpEnumValue(Iso3166CountryCode.GA, "GABON")]
		[McpEnumValue(Iso3166CountryCode.GM, "GAMBIA")]
		[McpEnumValue(Iso3166CountryCode.GE, "GEORGIA")]
		[McpEnumValue(Iso3166CountryCode.DE, "GERMANY")]
		[McpEnumValue(Iso3166CountryCode.GH, "GHANA")]
		[McpEnumValue(Iso3166CountryCode.GI, "GIBRALTAR")]
		[McpEnumValue(Iso3166CountryCode.GR, "GREECE")]
		[McpEnumValue(Iso3166CountryCode.GL, "GREENLAND")]
		[McpEnumValue(Iso3166CountryCode.GD, "GRENADA")]
		[McpEnumValue(Iso3166CountryCode.GP, "GUADELOUPE")]
		[McpEnumValue(Iso3166CountryCode.GU, "GUAM")]
		[McpEnumValue(Iso3166CountryCode.GT, "GUATEMALA")]
		[McpEnumValue(Iso3166CountryCode.GG, "GUERNSEY")]
		[McpEnumValue(Iso3166CountryCode.GN, "GUINEA")]
		[McpEnumValue(Iso3166CountryCode.GW, "GUINEA-BISSAU")]
		[McpEnumValue(Iso3166CountryCode.GY, "GUYANA")]
		[McpEnumValue(Iso3166CountryCode.HT, "HAITI")]
		[McpEnumValue(Iso3166CountryCode.HM, "HEARD ISLAND AND MCDONALD ISLANDS")]
		[McpEnumValue(Iso3166CountryCode.VA, "HOLY SEE (VATICAN CITY STATE)")]
		[McpEnumValue(Iso3166CountryCode.HN, "HONDURAS")]
		[McpEnumValue(Iso3166CountryCode.HK, "HONG KONG")]
		[McpEnumValue(Iso3166CountryCode.HU, "HUNGARY")]
		[McpEnumValue(Iso3166CountryCode.IS, "ICELAND")]
		[McpEnumValue(Iso3166CountryCode.IN, "INDIA")]
		[McpEnumValue(Iso3166CountryCode.ID, "INDONESIA")]
		[McpEnumValue(Iso3166CountryCode.IR, "IRAN, ISLAMIC REPUBLIC OF")]
		[McpEnumValue(Iso3166CountryCode.IQ, "IRAQ")]
		[McpEnumValue(Iso3166CountryCode.IE, "IRELAND")]
		[McpEnumValue(Iso3166CountryCode.IM, "ISLE OF MAN")]
		[McpEnumValue(Iso3166CountryCode.IL, "ISRAEL")]
		[McpEnumValue(Iso3166CountryCode.IT, "ITALY")]
		[McpEnumValue(Iso3166CountryCode.JM, "JAMAICA")]
		[McpEnumValue(Iso3166CountryCode.JP, "JAPAN")]
		[McpEnumValue(Iso3166CountryCode.JE, "JERSEY")]
		[McpEnumValue(Iso3166CountryCode.JO, "JORDAN")]
		[McpEnumValue(Iso3166CountryCode.KZ, "KAZAKHSTAN")]
		[McpEnumValue(Iso3166CountryCode.KE, "KENYA")]
		[McpEnumValue(Iso3166CountryCode.KI, "KIRIBATI")]
		[McpEnumValue(Iso3166CountryCode.KP, "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF")]
		[McpEnumValue(Iso3166CountryCode.KR, "KOREA, REPUBLIC OF")]
		[McpEnumValue(Iso3166CountryCode.KW, "KUWAIT")]
		[McpEnumValue(Iso3166CountryCode.KG, "KYRGYZSTAN")]
		[McpEnumValue(Iso3166CountryCode.LA, "LAO PEOPLE'S DEMOCRATIC REPUBLIC")]
		[McpEnumValue(Iso3166CountryCode.LV, "LATVIA")]
		[McpEnumValue(Iso3166CountryCode.LB, "LEBANON")]
		[McpEnumValue(Iso3166CountryCode.LS, "LESOTHO")]
		[McpEnumValue(Iso3166CountryCode.LR, "LIBERIA")]
		[McpEnumValue(Iso3166CountryCode.LY, "LIBYAN ARAB JAMAHIRIYA")]
		[McpEnumValue(Iso3166CountryCode.LI, "LIECHTENSTEIN")]
		[McpEnumValue(Iso3166CountryCode.LT, "LITHUANIA")]
		[McpEnumValue(Iso3166CountryCode.LU, "LUXEMBOURG")]
		[McpEnumValue(Iso3166CountryCode.MO, "MACAO")]
		[McpEnumValue(Iso3166CountryCode.MG, "MADAGASCAR")]
		[McpEnumValue(Iso3166CountryCode.MW, "MALAWI")]
		[McpEnumValue(Iso3166CountryCode.MY, "MALAYSIA")]
		[McpEnumValue(Iso3166CountryCode.MV, "MALDIVES")]
		[McpEnumValue(Iso3166CountryCode.ML, "MALI")]
		[McpEnumValue(Iso3166CountryCode.MT, "MALTA")]
		[McpEnumValue(Iso3166CountryCode.MH, "MARSHALL ISLANDS")]
		[McpEnumValue(Iso3166CountryCode.MQ, "MARTINIQUE")]
		[McpEnumValue(Iso3166CountryCode.MR, "MAURITANIA")]
		[McpEnumValue(Iso3166CountryCode.MU, "MAURITIUS")]
		[McpEnumValue(Iso3166CountryCode.YT, "MAYOTTE")]
		[McpEnumValue(Iso3166CountryCode.MX, "MEXICO")]
		[McpEnumValue(Iso3166CountryCode.FM, "MICRONESIA, FEDERATED STATES OF")]
		[McpEnumValue(Iso3166CountryCode.MD, "MOLDOVA, REPUBLIC OF")]
		[McpEnumValue(Iso3166CountryCode.MC, "MONACO")]
		[McpEnumValue(Iso3166CountryCode.MN, "MONGOLIA")]
		[McpEnumValue(Iso3166CountryCode.ME, "MONTENEGRO")]
		[McpEnumValue(Iso3166CountryCode.MS, "MONTSERRAT")]
		[McpEnumValue(Iso3166CountryCode.MA, "MOROCCO")]
		[McpEnumValue(Iso3166CountryCode.MZ, "MOZAMBIQUE")]
		[McpEnumValue(Iso3166CountryCode.MM, "MYANMAR")]
		[McpEnumValue(Iso3166CountryCode.NA, "NAMIBIA")]
		[McpEnumValue(Iso3166CountryCode.NR, "NAURU")]
		[McpEnumValue(Iso3166CountryCode.NP, "NEPAL")]
		[McpEnumValue(Iso3166CountryCode.NL, "NETHERLANDS")]
		[McpEnumValue(Iso3166CountryCode.AN, "NETHERLANDS ANTILLES")]
		[McpEnumValue(Iso3166CountryCode.NC, "NEW CALEDONIA")]
		[McpEnumValue(Iso3166CountryCode.NZ, "NEW ZEALAND")]
		[McpEnumValue(Iso3166CountryCode.NI, "NICARAGUA")]
		[McpEnumValue(Iso3166CountryCode.NE, "NIGER")]
		[McpEnumValue(Iso3166CountryCode.NG, "NIGERIA")]
		[McpEnumValue(Iso3166CountryCode.NU, "NIUE")]
		[McpEnumValue(Iso3166CountryCode.NF, "NORFOLK ISLAND")]
		[McpEnumValue(Iso3166CountryCode.MK, "NORTH MACEDONIA")]
		[McpEnumValue(Iso3166CountryCode.MP, "NORTHERN MARIANA ISLANDS")]
		[McpEnumValue(Iso3166CountryCode.NO, "NORWAY")]
		[McpEnumValue(Iso3166CountryCode.OM, "OMAN")]
		[McpEnumValue(Iso3166CountryCode.PK, "PAKISTAN")]
		[McpEnumValue(Iso3166CountryCode.PW, "PALAU")]
		[McpEnumValue(Iso3166CountryCode.PS, "PALESTINIAN TERRITORY, OCCUPIED")]
		[McpEnumValue(Iso3166CountryCode.PA, "PANAMA")]
		[McpEnumValue(Iso3166CountryCode.PG, "PAPUA NEW GUINEA")]
		[McpEnumValue(Iso3166CountryCode.PY, "PARAGUAY")]
		[McpEnumValue(Iso3166CountryCode.PE, "PERU")]
		[McpEnumValue(Iso3166CountryCode.PH, "PHILIPPINES")]
		[McpEnumValue(Iso3166CountryCode.PN, "PITCAIRN")]
		[McpEnumValue(Iso3166CountryCode.PL, "POLAND")]
		[McpEnumValue(Iso3166CountryCode.PT, "PORTUGAL")]
		[McpEnumValue(Iso3166CountryCode.PR, "PUERTO RICO")]
		[McpEnumValue(Iso3166CountryCode.QA, "QATAR")]
		[McpEnumValue(Iso3166CountryCode.RE, "REUNION")]
		[McpEnumValue(Iso3166CountryCode.RO, "ROMANIA")]
		[McpEnumValue(Iso3166CountryCode.RU, "RUSSIAN FEDERATION")]
		[McpEnumValue(Iso3166CountryCode.RW, "RWANDA")]
		[McpEnumValue(Iso3166CountryCode.SH, "SAINT HELENA")]
		[McpEnumValue(Iso3166CountryCode.KN, "SAINT KITTS AND NEVIS")]
		[McpEnumValue(Iso3166CountryCode.LC, "SAINT LUCIA")]
		[McpEnumValue(Iso3166CountryCode.PM, "SAINT PIERRE AND MIQUELON")]
		[McpEnumValue(Iso3166CountryCode.VC, "SAINT VINCENT AND THE GRENADINES")]
		[McpEnumValue(Iso3166CountryCode.WS, "SAMOA")]
		[McpEnumValue(Iso3166CountryCode.SM, "SAN MARINO")]
		[McpEnumValue(Iso3166CountryCode.ST, "SAO TOME AND PRINCIPE")]
		[McpEnumValue(Iso3166CountryCode.SA, "SAUDI ARABIA")]
		[McpEnumValue(Iso3166CountryCode.SN, "SENEGAL")]
		[McpEnumValue(Iso3166CountryCode.RS, "SERBIA")]
		[McpEnumValue(Iso3166CountryCode.SC, "SEYCHELLES")]
		[McpEnumValue(Iso3166CountryCode.SL, "SIERRA LEONE")]
		[McpEnumValue(Iso3166CountryCode.SG, "SINGAPORE")]
		[McpEnumValue(Iso3166CountryCode.SK, "SLOVAKIA")]
		[McpEnumValue(Iso3166CountryCode.SI, "SLOVENIA")]
		[McpEnumValue(Iso3166CountryCode.SB, "SOLOMON ISLANDS")]
		[McpEnumValue(Iso3166CountryCode.SO, "SOMALIA")]
		[McpEnumValue(Iso3166CountryCode.ZA, "SOUTH AFRICA")]
		[McpEnumValue(Iso3166CountryCode.GS, "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS")]
		[McpEnumValue(Iso3166CountryCode.ES, "SPAIN")]
		[McpEnumValue(Iso3166CountryCode.LK, "SRI LANKA")]
		[McpEnumValue(Iso3166CountryCode.SD, "SUDAN")]
		[McpEnumValue(Iso3166CountryCode.SR, "SURINAME")]
		[McpEnumValue(Iso3166CountryCode.SJ, "SVALBARD AND JAN MAYEN")]
		[McpEnumValue(Iso3166CountryCode.SZ, "SWAZILAND")]
		[McpEnumValue(Iso3166CountryCode.SE, "SWEDEN")]
		[McpEnumValue(Iso3166CountryCode.CH, "SWITZERLAND")]
		[McpEnumValue(Iso3166CountryCode.SY, "SYRIAN ARAB REPUBLIC")]
		[McpEnumValue(Iso3166CountryCode.TW, "TAIWAN, PROVINCE OF CHINA")]
		[McpEnumValue(Iso3166CountryCode.TJ, "TAJIKISTAN")]
		[McpEnumValue(Iso3166CountryCode.TZ, "TANZANIA, UNITED REPUBLIC OF")]
		[McpEnumValue(Iso3166CountryCode.TH, "THAILAND")]
		[McpEnumValue(Iso3166CountryCode.TL, "TIMOR-LESTE")]
		[McpEnumValue(Iso3166CountryCode.TG, "TOGO")]
		[McpEnumValue(Iso3166CountryCode.TK, "TOKELAU")]
		[McpEnumValue(Iso3166CountryCode.TO, "TONGA")]
		[McpEnumValue(Iso3166CountryCode.TT, "TRINIDAD AND TOBAGO")]
		[McpEnumValue(Iso3166CountryCode.TN, "TUNISIA")]
		[McpEnumValue(Iso3166CountryCode.TR, "TURKEY")]
		[McpEnumValue(Iso3166CountryCode.TM, "TURKMENISTAN")]
		[McpEnumValue(Iso3166CountryCode.TC, "TURKS AND CAICOS ISLANDS")]
		[McpEnumValue(Iso3166CountryCode.TV, "TUVALU")]
		[McpEnumValue(Iso3166CountryCode.UG, "UGANDA")]
		[McpEnumValue(Iso3166CountryCode.UA, "UKRAINE")]
		[McpEnumValue(Iso3166CountryCode.AE, "UNITED ARAB EMIRATES")]
		[McpEnumValue(Iso3166CountryCode.GB, "UNITED KINGDOM")]
		[McpEnumValue(Iso3166CountryCode.US, "UNITED STATES")]
		[McpEnumValue(Iso3166CountryCode.UM, "UNITED STATES MINOR OUTLYING ISLANDS")]
		[McpEnumValue(Iso3166CountryCode.UY, "URUGUAY")]
		[McpEnumValue(Iso3166CountryCode.UZ, "UZBEKISTAN")]
		[McpEnumValue(Iso3166CountryCode.VU, "VANUATU")]
		[McpEnumValue(Iso3166CountryCode.VE, "VENEZUELA")]
		[McpEnumValue(Iso3166CountryCode.VN, "VIET NAM")]
		[McpEnumValue(Iso3166CountryCode.VG, "VIRGIN ISLANDS, BRITISH")]
		[McpEnumValue(Iso3166CountryCode.VI, "VIRGIN ISLANDS, U.S.")]
		[McpEnumValue(Iso3166CountryCode.WF, "WALLIS AND FUTUNA")]
		[McpEnumValue(Iso3166CountryCode.EH, "WESTERN SAHARA")]
		[McpEnumValue(Iso3166CountryCode.YE, "YEMEN")]
		[McpEnumValue(Iso3166CountryCode.ZM, "ZAMBIA")]
		[McpEnumValue(Iso3166CountryCode.ZW, "ZIMBABWE")]
		public Iso3166CountryCode? Country = null;

		/// <summary>
		/// Nationality of the user. Must conform to ISO 3166.
		/// </summary>
		[McpParameter("Nationality", "Nationality of the user.")]
		[McpEnumValue(Iso3166CountryCode.AF, "AFGHANISTAN")]
		[McpEnumValue(Iso3166CountryCode.AX, "ÅLAND ISLANDS")]
		[McpEnumValue(Iso3166CountryCode.AL, "ALBANIA")]
		[McpEnumValue(Iso3166CountryCode.DZ, "ALGERIA")]
		[McpEnumValue(Iso3166CountryCode.AS, "AMERICAN SAMOA")]
		[McpEnumValue(Iso3166CountryCode.AD, "ANDORRA")]
		[McpEnumValue(Iso3166CountryCode.AO, "ANGOLA")]
		[McpEnumValue(Iso3166CountryCode.AI, "ANGUILLA")]
		[McpEnumValue(Iso3166CountryCode.AQ, "ANTARCTICA")]
		[McpEnumValue(Iso3166CountryCode.AG, "ANTIGUA AND BARBUDA")]
		[McpEnumValue(Iso3166CountryCode.AR, "ARGENTINA")]
		[McpEnumValue(Iso3166CountryCode.AM, "ARMENIA")]
		[McpEnumValue(Iso3166CountryCode.AW, "ARUBA")]
		[McpEnumValue(Iso3166CountryCode.AU, "AUSTRALIA")]
		[McpEnumValue(Iso3166CountryCode.AT, "AUSTRIA")]
		[McpEnumValue(Iso3166CountryCode.AZ, "AZERBAIJAN")]
		[McpEnumValue(Iso3166CountryCode.BS, "BAHAMAS")]
		[McpEnumValue(Iso3166CountryCode.BH, "BAHRAIN")]
		[McpEnumValue(Iso3166CountryCode.BD, "BANGLADESH")]
		[McpEnumValue(Iso3166CountryCode.BB, "BARBADOS")]
		[McpEnumValue(Iso3166CountryCode.BY, "BELARUS")]
		[McpEnumValue(Iso3166CountryCode.BE, "BELGIUM")]
		[McpEnumValue(Iso3166CountryCode.BZ, "BELIZE")]
		[McpEnumValue(Iso3166CountryCode.BJ, "BENIN")]
		[McpEnumValue(Iso3166CountryCode.BM, "BERMUDA")]
		[McpEnumValue(Iso3166CountryCode.BT, "BHUTAN")]
		[McpEnumValue(Iso3166CountryCode.BO, "BOLIVIA")]
		[McpEnumValue(Iso3166CountryCode.BA, "BOSNIA AND HERZEGOVINA")]
		[McpEnumValue(Iso3166CountryCode.BW, "BOTSWANA")]
		[McpEnumValue(Iso3166CountryCode.BV, "BOUVET ISLAND")]
		[McpEnumValue(Iso3166CountryCode.BR, "BRAZIL")]
		[McpEnumValue(Iso3166CountryCode.IO, "BRITISH INDIAN OCEAN TERRITORY")]
		[McpEnumValue(Iso3166CountryCode.BN, "BRUNEI DARUSSALAM")]
		[McpEnumValue(Iso3166CountryCode.BG, "BULGARIA")]
		[McpEnumValue(Iso3166CountryCode.BF, "BURKINA FASO")]
		[McpEnumValue(Iso3166CountryCode.BI, "BURUNDI")]
		[McpEnumValue(Iso3166CountryCode.KH, "CAMBODIA")]
		[McpEnumValue(Iso3166CountryCode.CM, "CAMEROON")]
		[McpEnumValue(Iso3166CountryCode.CA, "CANADA")]
		[McpEnumValue(Iso3166CountryCode.CV, "CAPE VERDE")]
		[McpEnumValue(Iso3166CountryCode.KY, "CAYMAN ISLANDS")]
		[McpEnumValue(Iso3166CountryCode.CF, "CENTRAL AFRICAN REPUBLIC")]
		[McpEnumValue(Iso3166CountryCode.TD, "CHAD")]
		[McpEnumValue(Iso3166CountryCode.CL, "CHILE")]
		[McpEnumValue(Iso3166CountryCode.CN, "CHINA")]
		[McpEnumValue(Iso3166CountryCode.CX, "CHRISTMAS ISLAND")]
		[McpEnumValue(Iso3166CountryCode.CC, "COCOS (KEELING) ISLANDS")]
		[McpEnumValue(Iso3166CountryCode.CO, "COLOMBIA")]
		[McpEnumValue(Iso3166CountryCode.KM, "COMOROS")]
		[McpEnumValue(Iso3166CountryCode.CG, "CONGO")]
		[McpEnumValue(Iso3166CountryCode.CD, "CONGO, THE DEMOCRATIC REPUBLIC OF THE")]
		[McpEnumValue(Iso3166CountryCode.CK, "COOK ISLANDS")]
		[McpEnumValue(Iso3166CountryCode.CR, "COSTA RICA")]
		[McpEnumValue(Iso3166CountryCode.CI, "COTE D'IVOIRE")]
		[McpEnumValue(Iso3166CountryCode.HR, "CROATIA")]
		[McpEnumValue(Iso3166CountryCode.CU, "CUBA")]
		[McpEnumValue(Iso3166CountryCode.CY, "CYPRUS")]
		[McpEnumValue(Iso3166CountryCode.CZ, "CZECH REPUBLIC")]
		[McpEnumValue(Iso3166CountryCode.DK, "DENMARK")]
		[McpEnumValue(Iso3166CountryCode.DJ, "DJIBOUTI")]
		[McpEnumValue(Iso3166CountryCode.DM, "DOMINICA")]
		[McpEnumValue(Iso3166CountryCode.DO, "DOMINICAN REPUBLIC")]
		[McpEnumValue(Iso3166CountryCode.EC, "ECUADOR")]
		[McpEnumValue(Iso3166CountryCode.EG, "EGYPT")]
		[McpEnumValue(Iso3166CountryCode.SV, "EL SALVADOR")]
		[McpEnumValue(Iso3166CountryCode.GQ, "EQUATORIAL GUINEA")]
		[McpEnumValue(Iso3166CountryCode.ER, "ERITREA")]
		[McpEnumValue(Iso3166CountryCode.EE, "ESTONIA")]
		[McpEnumValue(Iso3166CountryCode.ET, "ETHIOPIA")]
		[McpEnumValue(Iso3166CountryCode.FK, "FALKLAND ISLANDS (MALVINAS)")]
		[McpEnumValue(Iso3166CountryCode.FO, "FAROE ISLANDS")]
		[McpEnumValue(Iso3166CountryCode.FJ, "FIJI")]
		[McpEnumValue(Iso3166CountryCode.FI, "FINLAND")]
		[McpEnumValue(Iso3166CountryCode.FR, "FRANCE")]
		[McpEnumValue(Iso3166CountryCode.GF, "FRENCH GUIANA")]
		[McpEnumValue(Iso3166CountryCode.PF, "FRENCH POLYNESIA")]
		[McpEnumValue(Iso3166CountryCode.TF, "FRENCH SOUTHERN TERRITORIES")]
		[McpEnumValue(Iso3166CountryCode.GA, "GABON")]
		[McpEnumValue(Iso3166CountryCode.GM, "GAMBIA")]
		[McpEnumValue(Iso3166CountryCode.GE, "GEORGIA")]
		[McpEnumValue(Iso3166CountryCode.DE, "GERMANY")]
		[McpEnumValue(Iso3166CountryCode.GH, "GHANA")]
		[McpEnumValue(Iso3166CountryCode.GI, "GIBRALTAR")]
		[McpEnumValue(Iso3166CountryCode.GR, "GREECE")]
		[McpEnumValue(Iso3166CountryCode.GL, "GREENLAND")]
		[McpEnumValue(Iso3166CountryCode.GD, "GRENADA")]
		[McpEnumValue(Iso3166CountryCode.GP, "GUADELOUPE")]
		[McpEnumValue(Iso3166CountryCode.GU, "GUAM")]
		[McpEnumValue(Iso3166CountryCode.GT, "GUATEMALA")]
		[McpEnumValue(Iso3166CountryCode.GG, "GUERNSEY")]
		[McpEnumValue(Iso3166CountryCode.GN, "GUINEA")]
		[McpEnumValue(Iso3166CountryCode.GW, "GUINEA-BISSAU")]
		[McpEnumValue(Iso3166CountryCode.GY, "GUYANA")]
		[McpEnumValue(Iso3166CountryCode.HT, "HAITI")]
		[McpEnumValue(Iso3166CountryCode.HM, "HEARD ISLAND AND MCDONALD ISLANDS")]
		[McpEnumValue(Iso3166CountryCode.VA, "HOLY SEE (VATICAN CITY STATE)")]
		[McpEnumValue(Iso3166CountryCode.HN, "HONDURAS")]
		[McpEnumValue(Iso3166CountryCode.HK, "HONG KONG")]
		[McpEnumValue(Iso3166CountryCode.HU, "HUNGARY")]
		[McpEnumValue(Iso3166CountryCode.IS, "ICELAND")]
		[McpEnumValue(Iso3166CountryCode.IN, "INDIA")]
		[McpEnumValue(Iso3166CountryCode.ID, "INDONESIA")]
		[McpEnumValue(Iso3166CountryCode.IR, "IRAN, ISLAMIC REPUBLIC OF")]
		[McpEnumValue(Iso3166CountryCode.IQ, "IRAQ")]
		[McpEnumValue(Iso3166CountryCode.IE, "IRELAND")]
		[McpEnumValue(Iso3166CountryCode.IM, "ISLE OF MAN")]
		[McpEnumValue(Iso3166CountryCode.IL, "ISRAEL")]
		[McpEnumValue(Iso3166CountryCode.IT, "ITALY")]
		[McpEnumValue(Iso3166CountryCode.JM, "JAMAICA")]
		[McpEnumValue(Iso3166CountryCode.JP, "JAPAN")]
		[McpEnumValue(Iso3166CountryCode.JE, "JERSEY")]
		[McpEnumValue(Iso3166CountryCode.JO, "JORDAN")]
		[McpEnumValue(Iso3166CountryCode.KZ, "KAZAKHSTAN")]
		[McpEnumValue(Iso3166CountryCode.KE, "KENYA")]
		[McpEnumValue(Iso3166CountryCode.KI, "KIRIBATI")]
		[McpEnumValue(Iso3166CountryCode.KP, "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF")]
		[McpEnumValue(Iso3166CountryCode.KR, "KOREA, REPUBLIC OF")]
		[McpEnumValue(Iso3166CountryCode.KW, "KUWAIT")]
		[McpEnumValue(Iso3166CountryCode.KG, "KYRGYZSTAN")]
		[McpEnumValue(Iso3166CountryCode.LA, "LAO PEOPLE'S DEMOCRATIC REPUBLIC")]
		[McpEnumValue(Iso3166CountryCode.LV, "LATVIA")]
		[McpEnumValue(Iso3166CountryCode.LB, "LEBANON")]
		[McpEnumValue(Iso3166CountryCode.LS, "LESOTHO")]
		[McpEnumValue(Iso3166CountryCode.LR, "LIBERIA")]
		[McpEnumValue(Iso3166CountryCode.LY, "LIBYAN ARAB JAMAHIRIYA")]
		[McpEnumValue(Iso3166CountryCode.LI, "LIECHTENSTEIN")]
		[McpEnumValue(Iso3166CountryCode.LT, "LITHUANIA")]
		[McpEnumValue(Iso3166CountryCode.LU, "LUXEMBOURG")]
		[McpEnumValue(Iso3166CountryCode.MO, "MACAO")]
		[McpEnumValue(Iso3166CountryCode.MG, "MADAGASCAR")]
		[McpEnumValue(Iso3166CountryCode.MW, "MALAWI")]
		[McpEnumValue(Iso3166CountryCode.MY, "MALAYSIA")]
		[McpEnumValue(Iso3166CountryCode.MV, "MALDIVES")]
		[McpEnumValue(Iso3166CountryCode.ML, "MALI")]
		[McpEnumValue(Iso3166CountryCode.MT, "MALTA")]
		[McpEnumValue(Iso3166CountryCode.MH, "MARSHALL ISLANDS")]
		[McpEnumValue(Iso3166CountryCode.MQ, "MARTINIQUE")]
		[McpEnumValue(Iso3166CountryCode.MR, "MAURITANIA")]
		[McpEnumValue(Iso3166CountryCode.MU, "MAURITIUS")]
		[McpEnumValue(Iso3166CountryCode.YT, "MAYOTTE")]
		[McpEnumValue(Iso3166CountryCode.MX, "MEXICO")]
		[McpEnumValue(Iso3166CountryCode.FM, "MICRONESIA, FEDERATED STATES OF")]
		[McpEnumValue(Iso3166CountryCode.MD, "MOLDOVA, REPUBLIC OF")]
		[McpEnumValue(Iso3166CountryCode.MC, "MONACO")]
		[McpEnumValue(Iso3166CountryCode.MN, "MONGOLIA")]
		[McpEnumValue(Iso3166CountryCode.ME, "MONTENEGRO")]
		[McpEnumValue(Iso3166CountryCode.MS, "MONTSERRAT")]
		[McpEnumValue(Iso3166CountryCode.MA, "MOROCCO")]
		[McpEnumValue(Iso3166CountryCode.MZ, "MOZAMBIQUE")]
		[McpEnumValue(Iso3166CountryCode.MM, "MYANMAR")]
		[McpEnumValue(Iso3166CountryCode.NA, "NAMIBIA")]
		[McpEnumValue(Iso3166CountryCode.NR, "NAURU")]
		[McpEnumValue(Iso3166CountryCode.NP, "NEPAL")]
		[McpEnumValue(Iso3166CountryCode.NL, "NETHERLANDS")]
		[McpEnumValue(Iso3166CountryCode.AN, "NETHERLANDS ANTILLES")]
		[McpEnumValue(Iso3166CountryCode.NC, "NEW CALEDONIA")]
		[McpEnumValue(Iso3166CountryCode.NZ, "NEW ZEALAND")]
		[McpEnumValue(Iso3166CountryCode.NI, "NICARAGUA")]
		[McpEnumValue(Iso3166CountryCode.NE, "NIGER")]
		[McpEnumValue(Iso3166CountryCode.NG, "NIGERIA")]
		[McpEnumValue(Iso3166CountryCode.NU, "NIUE")]
		[McpEnumValue(Iso3166CountryCode.NF, "NORFOLK ISLAND")]
		[McpEnumValue(Iso3166CountryCode.MK, "NORTH MACEDONIA")]
		[McpEnumValue(Iso3166CountryCode.MP, "NORTHERN MARIANA ISLANDS")]
		[McpEnumValue(Iso3166CountryCode.NO, "NORWAY")]
		[McpEnumValue(Iso3166CountryCode.OM, "OMAN")]
		[McpEnumValue(Iso3166CountryCode.PK, "PAKISTAN")]
		[McpEnumValue(Iso3166CountryCode.PW, "PALAU")]
		[McpEnumValue(Iso3166CountryCode.PS, "PALESTINIAN TERRITORY, OCCUPIED")]
		[McpEnumValue(Iso3166CountryCode.PA, "PANAMA")]
		[McpEnumValue(Iso3166CountryCode.PG, "PAPUA NEW GUINEA")]
		[McpEnumValue(Iso3166CountryCode.PY, "PARAGUAY")]
		[McpEnumValue(Iso3166CountryCode.PE, "PERU")]
		[McpEnumValue(Iso3166CountryCode.PH, "PHILIPPINES")]
		[McpEnumValue(Iso3166CountryCode.PN, "PITCAIRN")]
		[McpEnumValue(Iso3166CountryCode.PL, "POLAND")]
		[McpEnumValue(Iso3166CountryCode.PT, "PORTUGAL")]
		[McpEnumValue(Iso3166CountryCode.PR, "PUERTO RICO")]
		[McpEnumValue(Iso3166CountryCode.QA, "QATAR")]
		[McpEnumValue(Iso3166CountryCode.RE, "REUNION")]
		[McpEnumValue(Iso3166CountryCode.RO, "ROMANIA")]
		[McpEnumValue(Iso3166CountryCode.RU, "RUSSIAN FEDERATION")]
		[McpEnumValue(Iso3166CountryCode.RW, "RWANDA")]
		[McpEnumValue(Iso3166CountryCode.SH, "SAINT HELENA")]
		[McpEnumValue(Iso3166CountryCode.KN, "SAINT KITTS AND NEVIS")]
		[McpEnumValue(Iso3166CountryCode.LC, "SAINT LUCIA")]
		[McpEnumValue(Iso3166CountryCode.PM, "SAINT PIERRE AND MIQUELON")]
		[McpEnumValue(Iso3166CountryCode.VC, "SAINT VINCENT AND THE GRENADINES")]
		[McpEnumValue(Iso3166CountryCode.WS, "SAMOA")]
		[McpEnumValue(Iso3166CountryCode.SM, "SAN MARINO")]
		[McpEnumValue(Iso3166CountryCode.ST, "SAO TOME AND PRINCIPE")]
		[McpEnumValue(Iso3166CountryCode.SA, "SAUDI ARABIA")]
		[McpEnumValue(Iso3166CountryCode.SN, "SENEGAL")]
		[McpEnumValue(Iso3166CountryCode.RS, "SERBIA")]
		[McpEnumValue(Iso3166CountryCode.SC, "SEYCHELLES")]
		[McpEnumValue(Iso3166CountryCode.SL, "SIERRA LEONE")]
		[McpEnumValue(Iso3166CountryCode.SG, "SINGAPORE")]
		[McpEnumValue(Iso3166CountryCode.SK, "SLOVAKIA")]
		[McpEnumValue(Iso3166CountryCode.SI, "SLOVENIA")]
		[McpEnumValue(Iso3166CountryCode.SB, "SOLOMON ISLANDS")]
		[McpEnumValue(Iso3166CountryCode.SO, "SOMALIA")]
		[McpEnumValue(Iso3166CountryCode.ZA, "SOUTH AFRICA")]
		[McpEnumValue(Iso3166CountryCode.GS, "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS")]
		[McpEnumValue(Iso3166CountryCode.ES, "SPAIN")]
		[McpEnumValue(Iso3166CountryCode.LK, "SRI LANKA")]
		[McpEnumValue(Iso3166CountryCode.SD, "SUDAN")]
		[McpEnumValue(Iso3166CountryCode.SR, "SURINAME")]
		[McpEnumValue(Iso3166CountryCode.SJ, "SVALBARD AND JAN MAYEN")]
		[McpEnumValue(Iso3166CountryCode.SZ, "SWAZILAND")]
		[McpEnumValue(Iso3166CountryCode.SE, "SWEDEN")]
		[McpEnumValue(Iso3166CountryCode.CH, "SWITZERLAND")]
		[McpEnumValue(Iso3166CountryCode.SY, "SYRIAN ARAB REPUBLIC")]
		[McpEnumValue(Iso3166CountryCode.TW, "TAIWAN, PROVINCE OF CHINA")]
		[McpEnumValue(Iso3166CountryCode.TJ, "TAJIKISTAN")]
		[McpEnumValue(Iso3166CountryCode.TZ, "TANZANIA, UNITED REPUBLIC OF")]
		[McpEnumValue(Iso3166CountryCode.TH, "THAILAND")]
		[McpEnumValue(Iso3166CountryCode.TL, "TIMOR-LESTE")]
		[McpEnumValue(Iso3166CountryCode.TG, "TOGO")]
		[McpEnumValue(Iso3166CountryCode.TK, "TOKELAU")]
		[McpEnumValue(Iso3166CountryCode.TO, "TONGA")]
		[McpEnumValue(Iso3166CountryCode.TT, "TRINIDAD AND TOBAGO")]
		[McpEnumValue(Iso3166CountryCode.TN, "TUNISIA")]
		[McpEnumValue(Iso3166CountryCode.TR, "TURKEY")]
		[McpEnumValue(Iso3166CountryCode.TM, "TURKMENISTAN")]
		[McpEnumValue(Iso3166CountryCode.TC, "TURKS AND CAICOS ISLANDS")]
		[McpEnumValue(Iso3166CountryCode.TV, "TUVALU")]
		[McpEnumValue(Iso3166CountryCode.UG, "UGANDA")]
		[McpEnumValue(Iso3166CountryCode.UA, "UKRAINE")]
		[McpEnumValue(Iso3166CountryCode.AE, "UNITED ARAB EMIRATES")]
		[McpEnumValue(Iso3166CountryCode.GB, "UNITED KINGDOM")]
		[McpEnumValue(Iso3166CountryCode.US, "UNITED STATES")]
		[McpEnumValue(Iso3166CountryCode.UM, "UNITED STATES MINOR OUTLYING ISLANDS")]
		[McpEnumValue(Iso3166CountryCode.UY, "URUGUAY")]
		[McpEnumValue(Iso3166CountryCode.UZ, "UZBEKISTAN")]
		[McpEnumValue(Iso3166CountryCode.VU, "VANUATU")]
		[McpEnumValue(Iso3166CountryCode.VE, "VENEZUELA")]
		[McpEnumValue(Iso3166CountryCode.VN, "VIET NAM")]
		[McpEnumValue(Iso3166CountryCode.VG, "VIRGIN ISLANDS, BRITISH")]
		[McpEnumValue(Iso3166CountryCode.VI, "VIRGIN ISLANDS, U.S.")]
		[McpEnumValue(Iso3166CountryCode.WF, "WALLIS AND FUTUNA")]
		[McpEnumValue(Iso3166CountryCode.EH, "WESTERN SAHARA")]
		[McpEnumValue(Iso3166CountryCode.YE, "YEMEN")]
		[McpEnumValue(Iso3166CountryCode.ZM, "ZAMBIA")]
		[McpEnumValue(Iso3166CountryCode.ZW, "ZIMBABWE")]
		public Iso3166CountryCode? Nationality = null;

		/// <summary>
		/// Birth date of the user.
		/// </summary>
		[McpDateParameter("Birth Date", "Birth date of the user.")]
		public DateTime? BirthDate = null;

		/// <summary>
		/// Gender of the user.
		/// </summary>
		[McpParameter("Gender", "Gender of the user.")]
		[McpEnumValue(UserInput.Gender.M, "Male")]
		[McpEnumValue(UserInput.Gender.F, "Female")]
		public Gender? Gender = null;
	}
}
