using System;

namespace Waher.Security
{
	/// <summary>
	/// Interface for legal identity attachments.
	/// </summary>
	public interface ILegalIdentityAttachment
	{
		/// <summary>
		/// Attachment ID
		/// </summary>
		string Id { get; }

		/// <summary>
		/// Legal ID of uploader of the attachment
		/// </summary>
		string LegalId { get; }

		/// <summary>
		/// Internet Content Type of binary attachment.
		/// </summary>
		string ContentType { get; }

		/// <summary>
		/// Filename of attachment.
		/// </summary>
		string FileName { get; }

		/// <summary>
		/// Binary signature of the attachment, generated by an approved legal identity of the account-holder.
		/// If no signature, attribute is null.
		/// </summary>
		byte[] Signature { get; }

		/// <summary>
		/// Timestamp of signature. If no signature, value is <see cref="DateTime.MinValue"/>
		/// </summary>
		DateTime Timestamp { get; }
	}
}
