<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Security\Waher.Security.E2ee\Waher.Security.E2ee.csproj" />
    <ProjectReference Include="..\..\Security\Waher.Security.EllipticCurves\Waher.Security.EllipticCurves.csproj" />
    <ProjectReference Include="..\..\Security\Waher.Security.PQC\Waher.Security.PQC.csproj" />
    <ProjectReference Include="..\..\Security\Waher.Security\Waher.Security.csproj" />
    <ProjectReference Include="..\Waher.Networking\Waher.Networking.csproj" />
  </ItemGroup>

</Project>
