using System;
using System.Collections.Generic;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;
using Waher.Content.Html.Elements;
using Waher.Events;
using Waher.Networking;
using Waher.Networking.HTTP;
using Waher.Networking.HTTP.Authentication;
using Waher.Runtime.Inventory;
using Waher.Runtime.Language;
using Waher.Runtime.Timing;
using Waher.Security;
using Waher.Security.JWT;
using Waher.Security.Users;
using Waher.Things.Metering;

namespace Waher.Things.Http
{
	/// <summary>
	/// HTTP module
	/// </summary>
	[Singleton]
	public class HttpModule : IModule, ITlsCertificateEndpoint
	{
		internal const string PostPrivileges = "Admin.SensorData.Post";

		private static HttpServer webServer;
		private static SensorDataReceptorResource api;
		private static LocalWebServerNode localWebServerNode;
		private static X509Certificate certificate;
		private static Scheduler scheduler;
		private static string rootFolder;

		/// <summary>
		/// Starts the module.
		/// </summary>
		public Task Start()
		{
			try
			{
				if (!Types.TryGetModuleParameter("HTTP", out object Obj) ||
					!(Obj is HttpServer WebServer))
				{
					Log.Error("Local Web Server not found.");
					return Task.CompletedTask;
				}

				webServer = WebServer;

				if (!Types.TryGetModuleParameter("Root", out Obj) ||
					!(Obj is string RootFolder))
				{
					Log.Warning("Root folder not defined.");
					rootFolder = null;
				}
				else
					rootFolder = RootFolder;

				if (!Types.TryGetModuleParameter("Scheduler", out Obj) ||
					!(Obj is Scheduler Scheduler))
				{
					Log.Warning("Scheduler not available.");
					scheduler = null;
				}
				else
					scheduler = Scheduler;

				HttpAuthenticationScheme[] Schemes = GetAuthenticationSchemes(PostPrivileges);

				api = new SensorDataReceptorResource("/ReportSensorData", Schemes);
				webServer.Register(api);
			}
			catch (Exception ex)
			{
				Log.Exception(ex);
			}
		
			return Task.CompletedTask;
		}

		/// <summary>
		/// Gets an array of authentication schemes available to authorize access to a
		/// web resource.
		/// </summary>
		/// <returns>Array of authentication schemes.</returns>
		public static HttpAuthenticationScheme[] GetAuthenticationSchemes()
		{
			return GetAuthenticationSchemes(Array.Empty<string>());
		}

		/// <summary>
		/// Gets an array of authentication schemes available to authorize access to a
		/// web resource.
		/// </summary>
		/// <param name="RequiredPrivilege">Required privilege.</param>
		/// <returns>Array of authentication schemes.</returns>
		public static HttpAuthenticationScheme[] GetAuthenticationSchemes(string RequiredPrivilege)
		{
			return GetAuthenticationSchemes(new string[] { RequiredPrivilege });
		}

		/// <summary>
		/// Gets an array of authentication schemes available to authorize access to a
		/// web resource.
		/// </summary>
		/// <param name="RequiredPrivileges">Required privileges.</param>
		/// <returns>Array of authentication schemes.</returns>
		public static HttpAuthenticationScheme[] GetAuthenticationSchemes(params string[] RequiredPrivileges)
		{
			List<HttpAuthenticationScheme> Schemes = new List<HttpAuthenticationScheme>();
			string Domain;
			int MinStrength;
			bool Encrypted;

			if (!Types.TryGetModuleParameter("X509", out object Obj) ||
				!(Obj is X509Certificate Certificate))
			{
				if (Types.TryGetModuleParameter("Realm", out Obj) &&
					Obj is string Realm)
				{
					Domain = Realm;
				}
				else
					Domain = null;

				Encrypted = false;
				MinStrength = 0;
			}
			else
			{
				certificate = Certificate;
				Encrypted = true;
				Domain = BinaryTcpClient.GetDomainFromSubject(Certificate.Subject);
				MinStrength = 128;
			}

			if (Types.TryGetModuleParameter("JWT", out JwtFactory JwtFactory) &&
				!JwtFactory.Disposed)
			{
				Schemes.Add(new JwtAuthentication(Encrypted, MinStrength, Domain, null, JwtFactory));   // Any JWT token generated by the server will suffice. Does not have to point to a registered user.
			}

			if (webServer.ClientCertificates != ClientCertificates.NotUsed)
				Schemes.Add(new MutualTlsAuthentication(Users.Source));

			Schemes.Add(new BasicAuthentication(Encrypted, MinStrength, Domain, Users.Source));
			Schemes.Add(new DigestAuthentication(Encrypted, MinStrength, DigestAlgorithm.MD5, Domain, Users.Source));
			Schemes.Add(new DigestAuthentication(Encrypted, MinStrength, DigestAlgorithm.SHA256, Domain, Users.Source));
			Schemes.Add(new DigestAuthentication(Encrypted, MinStrength, DigestAlgorithm.SHA3_256, Domain, Users.Source));
			Schemes.Add(new SessionAuthentication(webServer));

			if (RequiredPrivileges.Length == 0)
				return Schemes.ToArray();
			else
			{
				return new HttpAuthenticationScheme[]
				{
					new RequiredPrivileges(Schemes.ToArray(), RequiredPrivileges)
				};
			}
		}

		/// <summary>
		/// Checks if the Local Web Server Node has been created.
		/// </summary>
		public static async Task CheckLocalWebServerNode()
		{
			foreach (INode Node in await MeteringTopology.Root.ChildNodes)
			{
				if (Node is LocalWebServerNode LocalWebServerNode)
				{
					localWebServerNode = LocalWebServerNode;
					break;
				}
			}

			if (localWebServerNode is null)
			{
				localWebServerNode = new LocalWebServerNode()
				{
					NodeId = await (await Translator.GetDefaultLanguageAsync()).GetStringAsync(typeof(LocalWebServerNode), 1, "Local Web Server")
				};

				await MeteringTopology.Root.AddAsync(localWebServerNode);
			}
		}

		/// <summary>
		/// Stops the module.
		/// </summary>
		public Task Stop()
		{
			if (!(webServer is null) && !(api is null))
			{
				webServer.Unregister(api);
				webServer = null;
				api = null;
			}

			return Task.CompletedTask;
		}

		/// <summary>
		/// Updates the certificate used in mTLS negotiation.
		/// </summary>
		/// <param name="Certificate">Updated Certificate</param>
		public void UpdateCertificate(X509Certificate Certificate)
		{
			certificate = Certificate;
		}

		/// <summary>
		/// Current web server certificate.
		/// </summary>
		internal static X509Certificate Certificate => certificate;

		/// <summary>
		/// Web Server Root folder.
		/// </summary>
		internal static string RootFolder => rootFolder;

		/// <summary>
		/// Web Server instance.
		/// </summary>
		internal static HttpServer WebServer => webServer;

		/// <summary>
		/// Scheduler instance, if available.
		/// </summary>
		internal static Scheduler Scheduler => scheduler;

		/// <summary>
		/// Local web server node.
		/// </summary>
		internal static LocalWebServerNode LocalWebServerNode => localWebServerNode;
	}
}
