using System;
using System.Collections.Generic;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;
using Waher.Events;
using Waher.Networking;
using Waher.Networking.HTTP;
using Waher.Networking.HTTP.Authentication;
using Waher.Runtime.Inventory;
using Waher.Runtime.Language;
using Waher.Runtime.Timing;
using Waher.Security;
using Waher.Security.JWT;
using Waher.Security.Users;
using Waher.Things.Metering;

namespace Waher.Things.Http
{
	/// <summary>
	/// HTTP module
	/// </summary>
	[Singleton]
	public class HttpModule : IModule, ITlsCertificateEndpoint
	{
		internal const string PostPrivileges = "Admin.SensorData.Post";

		private static HttpServer webServer;
		private static SensorDataReceptorResource api;
		private static X509Certificate certificate;
		private static Scheduler scheduler;
		private static string rootFolder;

		/// <summary>
		/// Starts the module.
		/// </summary>
		public Task Start()
		{
			try
			{
				if (!Types.TryGetModuleParameter("HTTP", out object Obj) ||
					!(Obj is HttpServer WebServer))
				{
					Log.Error("Local Web Server not found.");
					return Task.CompletedTask;
				}

				webServer = WebServer;

				string Domain;
				int MinStrength;
				bool Encrypted;

				if (!Types.TryGetModuleParameter("X509", out Obj) ||
					!(Obj is X509Certificate Certificate))
				{
					Log.Warning("Web server encryption not enabled.");
					Encrypted = false;
					Domain = null;
					MinStrength = 0;
				}
				else
				{
					certificate = Certificate;
					Encrypted = true;
					Domain = BinaryTcpClient.GetDomainFromSubject(Certificate.Subject);
					MinStrength = 128;
				}

				if (!Types.TryGetModuleParameter("Root", out Obj) ||
					!(Obj is string RootFolder))
				{
					Log.Warning("Root folder not defined.");
					rootFolder = null;
				}
				else
					rootFolder = RootFolder;

				if (!Types.TryGetModuleParameter("Scheduler", out Obj) ||
					!(Obj is Scheduler Scheduler))
				{
					Log.Warning("Scheduler not available.");
					scheduler = null;
				}
				else
					scheduler = Scheduler;

				List<HttpAuthenticationScheme> Schemes = new List<HttpAuthenticationScheme>();

				if (Types.TryGetModuleParameter("JWT", out JwtFactory JwtFactory) &&
					!JwtFactory.Disposed)
				{
					Schemes.Add(new JwtAuthentication(Encrypted, MinStrength, Domain, null, JwtFactory));   // Any JWT token generated by the server will suffice. Does not have to point to a registered user.
				}

				if (webServer.ClientCertificates != ClientCertificates.NotUsed)
					Schemes.Add(new MutualTlsAuthentication(Users.Source));

				Schemes.Add(new BasicAuthentication(Encrypted, MinStrength, Domain, Users.Source));
				Schemes.Add(new DigestAuthentication(Encrypted, MinStrength, DigestAlgorithm.MD5, Domain, Users.Source));
				Schemes.Add(new DigestAuthentication(Encrypted, MinStrength, DigestAlgorithm.SHA256, Domain, Users.Source));
				Schemes.Add(new DigestAuthentication(Encrypted, MinStrength, DigestAlgorithm.SHA3_256, Domain, Users.Source));
				Schemes.Add(new RequiredUserPrivileges("User", "/Login.md", webServer, PostPrivileges));

				api = new SensorDataReceptorResource("/ReportSensorData", Schemes.ToArray());
				webServer.Register(api);
			}
			catch (Exception ex)
			{
				Log.Exception(ex);
			}
		
			return Task.CompletedTask;
		}

		/// <summary>
		/// Checks if the Local Web Server Node has been created.
		/// </summary>
		public static async Task CheckLocalWebServerNode()
		{
			bool HasLocalWebServerNode = false;

			foreach (INode Node in await MeteringTopology.Root.ChildNodes)
			{
				if (Node is LocalWebServerNode)
				{
					HasLocalWebServerNode = true;
					break;
				}
			}

			if (!HasLocalWebServerNode)
			{
				LocalWebServerNode Node = new LocalWebServerNode()
				{
					NodeId = await (await Translator.GetDefaultLanguageAsync()).GetStringAsync(typeof(LocalWebServerNode), 1, "Local Web Server")
				};

				await MeteringTopology.Root.AddAsync(Node);
			}
		}

		/// <summary>
		/// Stops the module.
		/// </summary>
		public Task Stop()
		{
			if (!(webServer is null) && !(api is null))
			{
				webServer.Unregister(api);
				webServer = null;
				api = null;
			}

			return Task.CompletedTask;
		}

		/// <summary>
		/// Updates the certificate used in mTLS negotiation.
		/// </summary>
		/// <param name="Certificate">Updated Certificate</param>
		public void UpdateCertificate(X509Certificate Certificate)
		{
			certificate = Certificate;
		}

		/// <summary>
		/// Current web server certificate.
		/// </summary>
		internal static X509Certificate Certificate => certificate;

		/// <summary>
		/// Web Server Root folder.
		/// </summary>
		internal static string RootFolder => rootFolder;

		/// <summary>
		/// Web Server instance.
		/// </summary>
		internal static HttpServer WebServer => webServer;

		/// <summary>
		/// Scheduler instance, if available.
		/// </summary>
		internal static Scheduler Scheduler => scheduler;
	}
}
