using System;
using System.Collections.Generic;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;
using Waher.Events;
using Waher.Networking;
using Waher.Networking.HTTP;
using Waher.Networking.HTTP.Authentication;
using Waher.Runtime.Inventory;
using Waher.Security.JWT;
using Waher.Security.Users;

namespace Waher.Things.Http
{
	/// <summary>
	/// HTTP module
	/// </summary>
	[Singleton]
	public class HttpModule : IModule
	{
		internal const string PostPrivileges = "Admin.SensorData.Post";

		private HttpServer webServer;
		private SensorDataReceptorResource api;

		/// <summary>
		/// Starts the module.
		/// </summary>
		public Task Start()
		{
			try
			{
				if (!Types.TryGetModuleParameter("HTTP", out object Obj) ||
					!(Obj is HttpServer WebServer))
				{
					Log.Error("Local Web Server not found.");
					return Task.CompletedTask;
				}

				this.webServer = WebServer;

				string Domain;
				int MinStrength;
				bool Encrypted;

				if (!Types.TryGetModuleParameter("X509", out Obj) ||
					!(Obj is X509Certificate Certificate))
				{
					Log.Warning("Web server encryption not enabled.");
					Encrypted = false;
					Domain = null;
					MinStrength = 0;
				}
				else
				{
					Encrypted = true;
					Domain = BinaryTcpClient.GetDomainFromSubject(Certificate.Subject);
					MinStrength = 128;
				}

				List<HttpAuthenticationScheme> Schemes = new List<HttpAuthenticationScheme>();

				if (Types.TryGetModuleParameter("JWT", out JwtFactory JwtFactory) &&
					!JwtFactory.Disposed)
				{
					Schemes.Add(new JwtAuthentication(Encrypted, MinStrength, Domain, null, JwtFactory));   // Any JWT token generated by the server will suffice. Does not have to point to a registered user.
				}

				if (this.webServer.ClientCertificates != ClientCertificates.NotUsed)
					Schemes.Add(new MutualTlsAuthentication(Users.Source));

				Schemes.Add(new BasicAuthentication(Encrypted, MinStrength, Domain, Users.Source));
				Schemes.Add(new DigestAuthentication(Encrypted, MinStrength, DigestAlgorithm.MD5, Domain, Users.Source));
				Schemes.Add(new DigestAuthentication(Encrypted, MinStrength, DigestAlgorithm.SHA256, Domain, Users.Source));
				Schemes.Add(new DigestAuthentication(Encrypted, MinStrength, DigestAlgorithm.SHA3_256, Domain, Users.Source));
				Schemes.Add(new RequiredUserPrivileges("User", "/Login.md", this.webServer, PostPrivileges));

				this.api = new SensorDataReceptorResource("/ReportSensorData", Schemes.ToArray());
				this.webServer.Register(this.api);
			}
			catch (Exception ex)
			{
				Log.Exception(ex);
			}

			return Task.CompletedTask;
		}

		/// <summary>
		/// Stops the module.
		/// </summary>
		public Task Stop()
		{
			if (!(this.webServer is null) && !(this.api is null))
			{
				this.webServer.Unregister(this.api);
				this.webServer = null;
				this.api = null;
			}

			return Task.CompletedTask;
		}
	}
}
