using System.Collections.Generic;
using Waher.Events;

namespace Waher.Networking.HTTP
{
	/// <summary>
	/// The requested resource MUST be accessed through the proxy given by the Location field. The Location field gives the URI of the proxy. 
	/// The recipient is expected to repeat this single request via the proxy. 305 responses MUST only be generated by origin servers.
	/// </summary>
	public class UseProxyException : HttpException
	{
		/// <summary>
		/// 305
		/// </summary>
		public const int Code = 305;

		/// <summary>
		/// Use Proxy
		/// </summary>
		public const string StatusMessage = "Use Proxy";

		/// <summary>
		/// The requested resource MUST be accessed through the proxy given by the Location field. The Location field gives the URI of the proxy. 
		/// The recipient is expected to repeat this single request via the proxy. 305 responses MUST only be generated by origin servers.
		/// </summary>
		/// <param name="Location">Location.</param>
		/// <param name="HeaderFields">HTTP Header fields to include in the response.</param>
		public UseProxyException(string Location, params KeyValuePair<string, string>[] HeaderFields)
			: base(Code, StatusMessage, HeaderFields.Join(new KeyValuePair<string, string>("Location", Location)))
		{
		}

		/// <summary>
		/// The requested resource MUST be accessed through the proxy given by the Location field. The Location field gives the URI of the proxy. 
		/// The recipient is expected to repeat this single request via the proxy. 305 responses MUST only be generated by origin servers.
		/// </summary>
		/// <param name="Location">Location.</param>
		/// <param name="ContentObject">Any content object to return. The object will be encoded before being sent.</param>
		/// <param name="HeaderFields">HTTP Header fields to include in the response.</param>
		public UseProxyException(string Location, object ContentObject, params KeyValuePair<string, string>[] HeaderFields)
			: base(Code, StatusMessage, ContentObject, HeaderFields.Join(new KeyValuePair<string, string>("Location", Location)))
		{
		}

		/// <summary>
		/// The requested resource MUST be accessed through the proxy given by the Location field. The Location field gives the URI of the proxy. 
		/// The recipient is expected to repeat this single request via the proxy. 305 responses MUST only be generated by origin servers.
		/// </summary>
		/// <param name="Location">Location.</param>
		/// <param name="Content">Any encoded content to return.</param>
		/// <param name="ContentType">The content type of <paramref name="Content"/>, if provided.</param>
		/// <param name="HeaderFields">HTTP Header fields to include in the response.</param>
		public UseProxyException(string Location, byte[] Content, string ContentType, params KeyValuePair<string, string>[] HeaderFields)
			: base(Code, StatusMessage, Content, ContentType, HeaderFields.Join(new KeyValuePair<string, string>("Location", Location)))
		{
		}
	}
}
