--
P21451-N1-T2-MIB DEFINITIONS ::= BEGIN
 
IMPORTS
    enterprises
        FROM RFC1155-SMI
    Integer32,OBJECT-TYPE
        FROM SNMPv2-SMI
    DisplayString
        FROM SNMPv2-TC
    TEXTUAL-CONVENTION
        FROM SNMPv2-TC;
 
 

--enterprises  1.3.6.1.4
NCAP  OBJECT IDENTIFIER ::= { enterprises 21451 }
 
NCAPone OBJECT IDENTIFIER ::= {NCAP  1}

TIMtwo  OBJECT IDENTIFIER ::= {NCAPone  2}
TIMdescrptiontwo  OBJECT IDENTIFIER ::={TIMtwo 0}

Sensorstwo  OBJECT IDENTIFIER ::= {TIMtwo  1}
TIMcpu2 OBJECT IDENTIFIER ::={TIMdescrptiontwo 1}


Slope2 OBJECT IDENTIFIER ::={Sensorstwo 1}

SlopeSwitch2 OBJECT-TYPE
SYNTAX      DisplayString
MAX-ACCESS  read-write
STATUS      current
DESCRIPTION
"Slope Switch"
::= {Slope2 1}

SlopeOut2 OBJECT-TYPE
SYNTAX      DisplayString
MAX-ACCESS  read-only
STATUS      current
DESCRIPTION
"Slpoe Out"
::= {Slope2 2}

Temperature2 OBJECT IDENTIFIER ::={Sensorstwo 2}

TemperatureSwitch OBJECT-TYPE
SYNTAX      DisplayString
MAX-ACCESS  read-write
STATUS      current
DESCRIPTION
"TemperatureSwitch"
::= {Temperature2 1}

TemperatureOut OBJECT-TYPE
SYNTAX      DisplayString
MAX-ACCESS  read-only
STATUS      current
DESCRIPTION 
"TemperatureOut"
::= {Temperature2 2}

Pressure2 OBJECT IDENTIFIER ::={Sensorstwo 3}

PressureSwitch2 OBJECT-TYPE
SYNTAX      DisplayString
MAX-ACCESS  read-write
STATUS      current
DESCRIPTION
"PressureSwitch"
::= {Pressure2 1}

PressureOut2 OBJECT-TYPE
SYNTAX      DisplayString
MAX-ACCESS  read-only
STATUS      current
DESCRIPTION
"PressureOut"
::= {Pressure2 2}

Light2 OBJECT IDENTIFIER ::={Sensorstwo 4}

LightSwitch2 OBJECT-TYPE
SYNTAX      DisplayString
MAX-ACCESS  read-write
STATUS      current
DESCRIPTION 
"light switch"
::= {Light2 1}

LightIn2 OBJECT-TYPE
SYNTAX      DisplayString
MAX-ACCESS  read-write
STATUS      current
DESCRIPTION
"PressureOut"
::= {Light2 2}


LCD2 OBJECT IDENTIFIER ::={Sensorstwo 5}

LCDdisplay2 OBJECT-TYPE
SYNTAX      DisplayString
MAX-ACCESS  read-write
STATUS      current
DESCRIPTION
"LCD dispaly"
::= {LCD2 1}

LCDIn2 OBJECT-TYPE
SYNTAX      DisplayString
MAX-ACCESS  read-write
STATUS      current
DESCRIPTION
"PressureOut"
::= {LCD2 2}

Buzzer2 OBJECT IDENTIFIER ::={Sensorstwo 6}
BuzzerSwitch2 OBJECT-TYPE
SYNTAX      DisplayString
MAX-ACCESS  read-write
STATUS      current
DESCRIPTION
"Buzzer2 Switch"
::= {Buzzer2 1}

BuzzerIn2 OBJECT-TYPE
SYNTAX      DisplayString
MAX-ACCESS  read-write
STATUS      current
DESCRIPTION
"Buzzer Output"
::= {Buzzer2 2}

AnaOne2 OBJECT IDENTIFIER ::={Sensorstwo 7}
AnaOneSwitch2 OBJECT-TYPE
SYNTAX      DisplayString
MAX-ACCESS  read-write
STATUS      current
DESCRIPTION
"Analogue One Switch"
::= {AnaOne2 1}

AnaOneOut2 OBJECT-TYPE
SYNTAX      DisplayString
MAX-ACCESS  read-only
STATUS      current
DESCRIPTION
"Analogue One Out"
::= {AnaOne2 2}


AnaTwo2 OBJECT IDENTIFIER ::={Sensorstwo 8}
AnaTwoSwitch2 OBJECT-TYPE
SYNTAX      DisplayString
MAX-ACCESS  read-write
STATUS      current
DESCRIPTION
"Analogue Two Switch"
::= {AnaTwo2 1}

AnaTwoOut2 OBJECT-TYPE
SYNTAX      DisplayString
MAX-ACCESS  read-only
STATUS      current
DESCRIPTION
"Analogue Two Out"
::= {AnaTwo2 2}

AnaThree2 OBJECT IDENTIFIER ::={Sensorstwo 9}
AnThreeSwitch2 OBJECT-TYPE
SYNTAX      DisplayString
MAX-ACCESS  read-write
STATUS      current
DESCRIPTION
"Analogue Three Switch"
::= {AnaThree2 1}

AnaThreeOut2 OBJECT-TYPE
SYNTAX      DisplayString
MAX-ACCESS  read-only
STATUS      current
DESCRIPTION
"Analogue Three Out"
::= {AnaThree2 2}

AnaFour2 OBJECT IDENTIFIER ::={Sensorstwo 10}
AnaFourSwitch2 OBJECT-TYPE
SYNTAX      DisplayString
MAX-ACCESS  read-write
STATUS      current
DESCRIPTION
"Analogue Four Switch"
::= {AnaFour2 1}

AnaFourOut2 OBJECT-TYPE
SYNTAX      DisplayString
MAX-ACCESS  read-only
STATUS      current
DESCRIPTION
"Analogue Four Out"
::= {AnaFour2 2}


DigOne2 OBJECT IDENTIFIER ::={Sensorstwo 11}
DigOneSwitch2 OBJECT-TYPE
SYNTAX      DisplayString
MAX-ACCESS  read-write
STATUS      current
DESCRIPTION
"Digital One Switch"
::= {DigOne2 1}

DigOneOut2 OBJECT-TYPE
SYNTAX      DisplayString
MAX-ACCESS  read-only
STATUS      current
DESCRIPTION
"Digital One Out"
::= {DigOne2 2}

DigTwo2 OBJECT IDENTIFIER ::={Sensorstwo 12}
DigTwoSwitch2 OBJECT-TYPE
SYNTAX      DisplayString
MAX-ACCESS  read-write
STATUS      current
DESCRIPTION
"Digital Two Switch"
::= {DigTwo2 1}

DigTwoOut2 OBJECT-TYPE
SYNTAX      DisplayString
MAX-ACCESS  read-only
STATUS      current
DESCRIPTION
"Digital Two Out"
::= {DigTwo2 2}

DigThree2 OBJECT IDENTIFIER ::={Sensorstwo 13}
DigThreeSwitch2 OBJECT-TYPE
SYNTAX      DisplayString
MAX-ACCESS  read-write
STATUS      current
DESCRIPTION
"Digital Three Switch"
::= {DigThree2 1}

DigThreeOut2 OBJECT-TYPE
SYNTAX      DisplayString
MAX-ACCESS  read-only
STATUS      current
DESCRIPTION
"Digital Three Out"
::= {DigThree2 2}





MainFrequency2 OBJECT-TYPE
SYNTAX      DisplayString
MAX-ACCESS  read-only
STATUS      current
DESCRIPTION
"the main frequency of TIM CPU"
::= {TIMcpu2 1}

Temperature2 OBJECT-TYPE
SYNTAX      DisplayString
MAX-ACCESS  read-only
STATUS      current
DESCRIPTION
"the temperature of TIM CPU"
::= {TIMcpu2 2}

Usage2 OBJECT-TYPE
SYNTAX      DisplayString
MAX-ACCESS  read-only
STATUS      current
DESCRIPTION
"the usage of TIM CPU"
::= {TIMcpu2 3}


END
