namespace Waher.Networking.XMPP
{
	/// <summary>
	/// Type of message received.
	/// </summary>
	public enum MessageType
	{
		/// <summary>
		/// The message is sent in the context of a one-to-one chat session.  Typically an interactive client will present a message
		/// of type "chat" in an interface that enables one-to-one chat between the two parties, including an appropriate conversation
		/// history.  Detailed recommendations regarding one-to-one chat sessions are provided under Section 5.1.
		/// </summary>
		Chat,

		/// <summary>
		/// The message is generated by an entity that experiences an error when processing a message received from another entity (for
		/// details regarding stanza error syntax, refer to [XMPP-CORE]).  A client that receives a message of type "error" SHOULD present an
		/// appropriate interface informing the original sender regarding the nature of the error.
		/// </summary>
		Error,

		/// <summary>
		/// The message is sent in the context of a multi-user chat environment (similar to that of [IRC]).  Typically a
		/// receiving client will present a message of type "groupchat" in an interface that enables many-to-many chat between the parties,
		/// including a roster of parties in the chatroom and an appropriate conversation history.  For detailed information about XMPP-based
		/// groupchat, refer to [XEP-0045].
		/// </summary>
		GroupChat,

		/// <summary>
		/// The message provides an alert, a notification, or other transient information to which no reply is expected (e.g.,
		/// news headlines, sports updates, near-real-time market data, or syndicated content).  Because no reply to the message is expected,
		/// typically a receiving client will present a message of type "headline" in an interface that appropriately differentiates the
		/// message from standalone messages, chat messages, and groupchat messages (e.g., by not providing the recipient with the ability to
		/// reply).  If the 'to' address is the bare JID, the receiving server SHOULD deliver the message to all of the recipient's available
		/// resources with non-negative presence priority and MUST deliver the message to at least one of those resources; if the 'to' address is
		/// a full JID and there is a matching resource, the server MUST deliver the message to that resource; otherwise the server MUST
		/// either silently ignore the message or return an error (see Section 8).
		/// </summary>
		Headline,

		/// <summary>
		/// The message is a standalone message that is sent outside the context of a one-to-one conversation or groupchat, and to
		/// which it is expected that the recipient will reply.  Typically a receiving client will present a message of type "normal" in an
		/// interface that enables the recipient to reply, but without a conversation history.  The default value of the 'type' attribute
		/// is "normal".
		/// </summary>
		Normal,
	}
}
