<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
		<Authors>Peter Waher</Authors>
		<Company>Waher Data AB</Company>
		<Product>Waher.IoTGateway</Product>
		<Description>Library that tunnels database requests to a remote server using the same library to receive incoming connections. Storage and retrieval is based solely on meta-data provided through the corresponding class definitions. Object serializers are created dynamically. Dynamic code is compiled.</Description>
		<Copyright>Copyright © Waher Data AB 2026. All rights reserved.</Copyright>
		<PackageLicenseUrl />
		<PackageProjectUrl>https://github.com/PeterWaher/IoTGateway/tree/master/Persistence/Waher.Persistence.Remote</PackageProjectUrl>
		<RepositoryUrl>https://github.com/PeterWaher/IoTGateway</RepositoryUrl>
		<RepositoryType>GitHub</RepositoryType>
		<PackageTags>persistence queue enryption file storage</PackageTags>
		<NeutralLanguage>English</NeutralLanguage>
		<AssemblyVersion>1.0.0</AssemblyVersion>
		<FileVersion>1.0.0</FileVersion>
		<Version>1.0.0</Version>
		<PackageIconUrl />
		<PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
		<PackageIcon>Icon_64x64.png</PackageIcon>
	</PropertyGroup>
	<PropertyGroup>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<DefineConstants>$(DefineConstants);COMPILED</DefineConstants>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<DefineConstants>$(DefineConstants);COMPILED</DefineConstants>
	</PropertyGroup>
	<ItemGroup>
	  <ProjectReference Include="..\..\Networking\Waher.Networking.E2ee\Waher.Networking.E2ee.csproj" />
	  <ProjectReference Include="..\..\Networking\Waher.Networking\Waher.Networking.csproj" />
	  <ProjectReference Include="..\Waher.Persistence.Serialization.Compiled\Waher.Persistence.Serialization.Compiled.csproj" />
	  <ProjectReference Include="..\Waher.Persistence\Waher.Persistence.csproj" />
	</ItemGroup>
	<ItemGroup>
		<None Include="..\..\Images\Icon_64x64.png">
			<Pack>True</Pack>
			<PackagePath />
		</None>
		<None Include="..\..\LICENSE.txt">
			<Pack>True</Pack>
			<PackagePath />
		</None>
	</ItemGroup>

</Project>
