<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<AssemblyVersion>1.0.1</AssemblyVersion>
		<FileVersion>1.0.1</FileVersion>
		<Version>1.0.1</Version>
		<Authors>Peter Waher</Authors>
		<Company>Waher Data AB</Company>
		<Product>Waher.IoTGateway</Product>
		<Description>Library that provides an MCP Server for the Event Log. It contains tools for logging and searching for events, as well as prompts to identify sensitive information in the log.</Description>
		<Copyright>Copyright © Waher Data AB 2026. All rights reserved.</Copyright>
		<PackageProjectUrl>https://github.com/PeterWaher/IoTGateway/tree/master/Networking/Waher.Networking.HTTP.Mcp</PackageProjectUrl>
		<PackageIcon>Icon_64x64.png</PackageIcon>
		<RepositoryUrl>https://github.com/PeterWaher/IoTGateway</RepositoryUrl>
		<RepositoryType>GitHub</RepositoryType>
		<PackageTags>networking communication http MCP</PackageTags>
	</PropertyGroup>
	<PropertyGroup>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\..\Images\Icon_64x64.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
    <PackageReference Include="SkiaSharp" Version="4.151.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Content\Waher.Content.Images\Waher.Content.Images.csproj" />
    <ProjectReference Include="..\..\Content\Waher.Content.Toon\Waher.Content.Toon.csproj" />
    <ProjectReference Include="..\..\Content\Waher.Content.Xml\Waher.Content.Xml.csproj" />
    <ProjectReference Include="..\..\Content\Waher.Content\Waher.Content.csproj" />
    <ProjectReference Include="..\..\Runtime\Waher.Runtime.Counters\Waher.Runtime.Counters.csproj" />
    <ProjectReference Include="..\..\Script\Waher.Script.Content\Waher.Script.Content.csproj" />
    <ProjectReference Include="..\..\Script\Waher.Script.Graphs\Waher.Script.Graphs.csproj" />
    <ProjectReference Include="..\..\Script\Waher.Script\Waher.Script.csproj" />
    <ProjectReference Include="..\..\Things\Waher.Things.Http\Waher.Things.Http.csproj" />
    <ProjectReference Include="..\Waher.Networking.HTTP.JsonRpc\Waher.Networking.HTTP.JsonRpc.csproj" />
    <ProjectReference Include="..\Waher.Networking.HTTP.OAuth\Waher.Networking.HTTP.OAuth.csproj" />
    <ProjectReference Include="..\Waher.Networking.HTTP\Waher.Networking.HTTP.csproj" />
  </ItemGroup>

</Project>
