using System;
using System.Text;
using Waher.Persistence;
using Waher.Persistence.Attributes;
using Waher.Runtime.Inventory;
using Waher.Security.CallStack;

namespace Waher.Networking.XMPP.Contracts
{
	/// <summary>
	/// Contains information about a legal identity generated by the client.
	/// </summary>
	[CollectionName("LegalIdentityStates")]
	[TypeName(TypeNameSerialization.None)]
	[Index("BareJid", "LegalId")]
	[Index("BareJid", "State", "Timestamp")]
	[Singleton]
	public class LegalIdentityState : IEncryptedProperties
	{
		private static ICallStackCheck[] approvedSources = null;

		private string objectId = null;
		private CaseInsensitiveString bareJid = CaseInsensitiveString.Empty;
		private CaseInsensitiveString legalId = CaseInsensitiveString.Empty;
		private byte[] publicKey = null;
		private string keyName = null;
		private string keyNamespace = null;
		private byte[] privateKey = null;
		private IdentityState state = IdentityState.Created;
		private DateTime timestamp = DateTime.MinValue;

		/// <summary>
		/// Contains information about a legal identity generated by the client.
		/// </summary>
		public LegalIdentityState()
		{
		}

		/// <summary>
		/// Contains information about a legal identity generated by the client.
		/// </summary>
		/// <param name="LegalId">Legal identity.</param>
		public LegalIdentityState(string LegalId)
		{
			this.legalId = LegalId;
		}

		/// <summary>
		/// Object ID
		/// </summary>
		[ObjectId]
		public string ObjectId
		{
			get => this.objectId;
			set => this.objectId = value;
		}

		/// <summary>
		/// Bare JID of client applying for the identity.
		/// </summary>
		public CaseInsensitiveString BareJid
		{
			get => this.bareJid;
			set => this.bareJid = value;
		}

		/// <summary>
		/// Identity string assigned to the legal identity.
		/// </summary>
		public CaseInsensitiveString LegalId
		{
			get => this.legalId;
			set => this.legalId = value;
		}

		/// <summary>
		/// Public Key used by the cryptographic algororithm used to sign the identity application.
		/// </summary>
		[DefaultValueNull]
		public byte[] PublicKey
		{
			get => this.publicKey;
			set => this.publicKey = value;
		}

		/// <summary>
		/// Name of key algorithm used when the identity was created.
		/// </summary>
		[DefaultValueNull]
		public string KeyName
		{
			get => this.keyName;
			set => this.keyName = value;
		}

		/// <summary>
		/// Namespace of key algorithm used when the identity was created.
		/// </summary>
		[DefaultValueNull]
		public string KeyNamespace
		{
			get => this.keyNamespace;
			set => this.keyNamespace = value;
		}

		/// <summary>
		/// If a private key snapshot is available for the legal identity.
		/// </summary>
		public bool HasPrivateKey => !(this.privateKey is null);

		/// <summary>
		/// Private key snapshot stored with the legal identity.
		/// </summary>
		[DefaultValueNull]
		[Encrypted(32)]
		public byte[] PrivateKey
		{
			get
			{
				AssertAllowed();
				return this.privateKey;
			}

			set
			{
				if (!(this.privateKey is null))
					AssertAllowed();

				this.privateKey = value;
			}
		}

		/// <summary>
		/// State of the legal identity.
		/// </summary>
		public IdentityState State
		{
			get => this.state;
			set => this.state = value;
		}

		/// <summary>
		/// Timestamp when the legal identity was created or last updated.
		/// </summary>
		public DateTime Timestamp
		{
			get => this.timestamp;
			set => this.timestamp = value;
		}

		/// <summary>
		/// Array of properties that are encrypted.
		/// </summary>
		public string[] EncryptedProperties => new string[]
		{
			nameof(this.PrivateKey)
		};

		/// <summary>
		/// If access to sensitive properties is only accessible from a set of approved sources.
		/// </summary>
		/// <param name="ApprovedSources">Approved sources.</param>
		/// <exception cref="NotSupportedException">If trying to change previously set sources.</exception>
		public static void SetAllowedSources(ICallStackCheck[] ApprovedSources)
		{
			if (!(approvedSources is null))
				throw new NotSupportedException("Changing approved sources not permitted.");

			approvedSources = ApprovedSources;
		}

		private static void AssertAllowed()
		{
			if (!(approvedSources is null))
				Assert.CallFromSource(approvedSources);
		}

		/// <inheritdoc/>
		public override string ToString()
		{
			StringBuilder sb = new StringBuilder();

			sb.Append(this.bareJid);
			sb.Append(", ");
			sb.Append(this.legalId);
			sb.Append(", ");
			sb.Append(this.state.ToString());
			sb.Append(", ");
			sb.Append(this.timestamp.ToString());

			if (!(this.publicKey is null))
			{
				sb.Append(", ");
				sb.Append(Convert.ToBase64String(this.publicKey));
			}

			if (!string.IsNullOrEmpty(this.keyName))
			{
				sb.Append(", ");
				sb.Append(this.keyName);
			}

			if (!string.IsNullOrEmpty(this.keyNamespace))
			{
				sb.Append(", ");
				sb.Append(this.keyNamespace);
			}

			if (!(this.privateKey is null))
			{
				sb.Append(", PrivateKey");
			}

			return sb.ToString();
		}
	}
}
