using System;
using System.Text;
using System.Threading.Tasks;
using System.Xml;
using Waher.Content.Xml;
using Waher.Networking.XMPP.Contracts.HumanReadable;
using Waher.Persistence;
using Waher.Persistence.Attributes;
using Waher.Script;

namespace Waher.Networking.XMPP.Contracts
{
	/// <summary>
	/// Role-reference contractual parameter
	/// </summary>
	public class RoleParameter : Parameter
	{
		private string role = string.Empty;
		private string property = string.Empty;
		private string attachmentId = null;
		private string attachmentLegalId = null;
		private string attachmentContentType = string.Empty;
		private string attachmentFileName = null;
		private byte[] attachmentSignature = null;
		private DateTime attachmentTimestamp = DateTime.MinValue;
		private string attachmentUrl = null;
		private string propertyValue = null;
		private string contentType = null;
		private object decodedValue = null;
		private byte[] encodedValue = null;
		private int index = 0;
		private bool required = false;

		/// <summary>
		/// Parameter value.
		/// </summary>
		public override object ObjectValue
		{
			get
			{
				if (this.decodedValue is null)
					return this.propertyValue;
				else
					return this.decodedValue;
			}
		}

		/// <summary>
		/// URL to attachment
		/// </summary>
		public string AttachmentUrl
		{
			get => this.attachmentUrl;
			set => this.attachmentUrl = value;
		}

		/// <summary>
		/// Attachment ID
		/// </summary>
		public CaseInsensitiveString AttachmentId
		{
			get => this.attachmentId;
			set => this.attachmentId = value;
		}

		/// <summary>
		/// Legal ID of uploader of the attachment
		/// </summary>
		public CaseInsensitiveString AttachmentLegalId
		{
			get => this.attachmentLegalId;
			set => this.attachmentLegalId = value;
		}

		/// <summary>
		/// Internet Content Type of binary attachment.
		/// </summary>
		public string AttachmentContentType
		{
			get => this.attachmentContentType;
			set => this.attachmentContentType = value;
		}

		/// <summary>
		/// Filename of attachment.
		/// </summary>
		public string AttachmentFileName
		{
			get => this.attachmentFileName;
			set => this.attachmentFileName = value;
		}

		/// <summary>
		/// Binary signature of the attachment, generated by an approved legal identity of the account-holder.
		/// If no signature, attribute is null.
		/// </summary>
		[DefaultValueNull]
		public byte[] AttachmentSignature
		{
			get => this.attachmentSignature;
			set => this.attachmentSignature = value;
		}

		/// <summary>
		/// Timestamp of signature. If no signature, value is <see cref="DateTime.MinValue"/>
		/// </summary>
		[DefaultValueDateTimeMinValue]
		public DateTime AttachmentTimestamp
		{
			get => this.attachmentTimestamp;
			set => this.attachmentTimestamp = value;
		}

		/// <summary>
		/// If the value is an attachment reference.
		/// </summary>
		public bool HasAttachmentValue => !(this.decodedValue is null);

		/// <summary>
		/// Name of role the parameter references.
		/// </summary>
		public string Role
		{
			get => this.role;
			set => this.role = value;
		}

		/// <summary>
		/// 1-based Role index. 1=First signatory having the role, 2=second, etc.
		/// </summary>
		public int Index
		{
			get => this.index;
			set => this.index = value;
		}

		/// <summary>
		/// Name of property of signatory having the corresponding role.
		/// </summary>
		public string Property
		{
			get => this.property;
			set => this.property = value;
		}

		/// <summary>
		/// If parameter is required to exist for contract to be valid.
		/// </summary>
		public bool Required
		{
			get => this.required;
			set => this.required = value;
		}

		/// <summary>
		/// Role parameter value.
		/// </summary>
		public string Value => this.propertyValue;

		/// <summary>
		/// String representation of value.
		/// </summary>
		public override string StringValue
		{
			get
			{
				if (this.HasAttachmentValue)
					return this.attachmentId;
				else
					return this.propertyValue ?? string.Empty;
			}

			set
			{
				this.propertyValue = value;
				this.attachmentId = null;
				this.attachmentLegalId = null;
				this.attachmentContentType = null;
				this.attachmentFileName = null;
				this.attachmentSignature = null;
				this.attachmentTimestamp = DateTime.MinValue;
				this.attachmentUrl = null;
				this.decodedValue = null;
				this.ProtectedValue = null;
			}
		}

		/// <summary>
		/// Internet Content-Type (may include wildcards), if parameter refers to an identity attachment.
		/// </summary>
		public string ContentType
		{
			get => this.contentType;
			set => this.contentType = value;
		}

		/// <summary>
		/// If the value refers to an attachment.
		/// </summary>
		public bool RefersToAttachment => !string.IsNullOrEmpty(this.contentType);

		/// <summary>
		/// Parameter type name, corresponding to the local name of the parameter element in XML.
		/// </summary>
		public override string ParameterType => "roleParameter";

		/// <summary>
		/// Serializes the parameter, in normalized form.
		/// </summary>
		/// <param name="Xml">XML Output</param>
		/// <param name="UsingTemplate">If the XML is for creating a contract using a template.</param>
		public override void Serialize(StringBuilder Xml, bool UsingTemplate)
		{
			if (!UsingTemplate)
			{
				Xml.Append("<roleParameter");

				if (!string.IsNullOrEmpty(this.contentType))
				{
					Xml.Append(" contentType=\"");
					Xml.Append(XML.Encode(this.contentType.Normalize(NormalizationForm.FormC)));
					Xml.Append('"');
				}

				if (!string.IsNullOrEmpty(this.Expression))
				{
					Xml.Append(" exp=\"");
					Xml.Append(XML.Encode(this.Expression.Normalize(NormalizationForm.FormC)));
					Xml.Append('"');
				}

				if (!string.IsNullOrEmpty(this.Guide))
				{
					Xml.Append(" guide=\"");
					Xml.Append(XML.Encode(this.Guide.Normalize(NormalizationForm.FormC)));
					Xml.Append('"');
				}

				Xml.Append(" index=\"");
				Xml.Append(this.index.ToString());
				Xml.Append('"');

				Xml.Append(" name=\"");
				Xml.Append(XML.Encode(this.Name.Normalize(NormalizationForm.FormC)));
				Xml.Append('"');

				Xml.Append(" property=\"");
				Xml.Append(XML.Encode(this.property.Normalize(NormalizationForm.FormC)));
				Xml.Append('"');

				if (this.Protection != ProtectionLevel.Normal)
				{
					Xml.Append(" protection=\"");
					Xml.Append(this.Protection.ToString());
					Xml.Append('"');
				}

				if (this.required)
					Xml.Append(" required=\"true\"");

				Xml.Append(" role=\"");
				Xml.Append(XML.Encode(this.role.Normalize(NormalizationForm.FormC)));
				Xml.Append('"');

				if (UsingTemplate || this.Descriptions is null || this.Descriptions.Length == 0)
					Xml.Append("/>");
				else
				{
					Xml.Append('>');

					foreach (HumanReadableText Description in this.Descriptions)
						Description.Serialize(Xml, "description", null);

					Xml.Append("</roleParameter>");
				}
			}
		}

		/// <summary>
		/// Checks if the parameter value is valid.
		/// </summary>
		/// <param name="Variables">Collection of parameter values.</param>
		/// <param name="Client">Connected contracts client. If offline or null, partial validation in certain cases will be performed.</param>
		/// <returns>Error message, if parameter value is not valid, null if valid.</returns>
		public override Task<bool> IsParameterValid(Variables Variables, ContractsClient Client)
		{
			this.ErrorReason = null;
			this.ErrorText = null;

			return Task.FromResult(true);
		}

		/// <summary>
		/// Populates a variable collection with the value of the parameter.
		/// </summary>
		/// <param name="Variables">Variable collection.</param>
		public override void Populate(Variables Variables)
		{
			if (this.decodedValue is null)
				Variables[this.Name] = this.propertyValue;
			else
				Variables[this.Name] = this.decodedValue;
		}

		/// <summary>
		/// Sets the parameter value.
		/// </summary>
		/// <param name="Value">Value</param>
		/// <exception cref="ArgumentException">If <paramref name="Value"/> is not of the correct type.</exception>
		public override void SetValue(object Value)
		{
			this.StringValue = Value?.ToString();
		}

		/// <summary>
		/// Sets the value of the role parameter.
		/// </summary>
		/// <param name="Value">Role parameter value.</param>
		/// <param name="EncodedValue">Encoded attachment value.</param>
		/// <param name="DecodedValue">Decoded attachment value.</param>
		internal void SetValue(Attachment Value, byte[] EncodedValue,
			object DecodedValue)
		{
			this.SetValue(Value.Id, Value.LegalId, Value.ContentType, Value.FileName,
				Value.Signature, Value.Timestamp, Value.Url, EncodedValue, DecodedValue);
		}

		/// <summary>
		/// Sets the value of the role parameter.
		/// </summary>
		/// <param name="Id">Attachment ID.</param>
		/// <param name="LegalId">Legal ID of uploader of the attachment.</param>
		/// <param name="ContentType">Internet Content Type of binary attachment.</param>
		/// <param name="FileName">Filename of attachment.</param>
		/// <param name="Signature">Binary signature of the attachment.</param>
		/// <param name="Timestamp">Timestamp of signature.</param>
		/// <param name="Url">URL to attachment.</param>
		/// <param name="EncodedValue">Encoded attachment value.</param>
		/// <param name="DecodedValue">Decoded attachment value.</param>
		internal void SetValue(CaseInsensitiveString Id, CaseInsensitiveString LegalId,
			string ContentType, string FileName, byte[] Signature, DateTime Timestamp,
			string Url, byte[] EncodedValue, object DecodedValue)
		{
			this.attachmentId = Id;
			this.attachmentLegalId = LegalId;
			this.attachmentContentType = ContentType;
			this.attachmentFileName = FileName;
			this.attachmentSignature = Signature;
			this.attachmentTimestamp = Timestamp;
			this.attachmentUrl = Url;
			this.encodedValue = EncodedValue;
			this.decodedValue = DecodedValue;
			this.propertyValue = null;
			this.ProtectedValue = null;
		}

		/// <summary>
		/// Encoded attachment value.
		/// </summary>
		public byte[] EncodedAttachment => this.encodedValue;

		/// <summary>
		/// Sets the minimum value allowed by the parameter.
		/// </summary>
		/// <param name="Value">Minimum value.</param>
		/// <param name="Inclusive">If the value is included in the range. If null, keeps the original value.</param>
		public override void SetMinValue(object Value, bool? Inclusive)
		{
			throw new InvalidOperationException("Minimum value for Role parameter types not supported.");
		}

		/// <summary>
		/// Sets the maximum value allowed by the parameter.
		/// </summary>
		/// <param name="Value">Maximum value.</param>
		/// <param name="Inclusive">If the value is included in the range. If null, keeps the original value.</param>
		public override void SetMaxValue(object Value, bool? Inclusive)
		{
			throw new InvalidOperationException("Maximum value for Role parameter types not supported.");
		}

		/// <summary>
		/// Imports parameter values from its XML definition.
		/// </summary>
		/// <param name="Xml">XML definition.</param>
		/// <returns>If import was successful.</returns>
		public override Task<bool> Import(XmlElement Xml)
		{
			this.Role = XML.Attribute(Xml, "role");
			this.Index = XML.Attribute(Xml, "index", 0);
			this.Property = XML.Attribute(Xml, "property");
			this.Required = XML.Attribute(Xml, "required", false);
			this.ContentType = XML.Attribute(Xml, "contentType");

			return base.Import(Xml);
		}

	}
}
