<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
		<Authors>Peter Waher</Authors>
		<Company>Waher Data AB</Company>
		<Product>Waher.IoTGateway</Product>
		<Description>Class library containing a basic abstraction for End-to-End Encryption (E2EE) using hybrid ciphers (consisting of pairs of symmetric and asymmetric ciphers, where the asymmetric cipher is used to derive shared secrets for the symmetric ciphers).</Description>
		<Copyright>Copyright © Waher Data AB 2018-2026. All rights reserved.</Copyright>
		<PackageLicenseUrl></PackageLicenseUrl>
		<PackageProjectUrl>https://github.com/PeterWaher/IoTGateway/tree/master/Security/Waher.Security.E2ee</PackageProjectUrl>
		<PackageIconUrl></PackageIconUrl>
		<RepositoryUrl>https://github.com/PeterWaher/IoTGateway</RepositoryUrl>
		<RepositoryType>GitHub</RepositoryType>
		<PackageTags>security End-to-End Encryption</PackageTags>
		<NeutralLanguage>English</NeutralLanguage>
		<AssemblyVersion>1.0.0</AssemblyVersion>
		<FileVersion>1.0.0</FileVersion>
		<Version>1.0.0</Version>
		<PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
		<PackageIcon>Icon_64x64.png</PackageIcon>
	</PropertyGroup>
	<PropertyGroup>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>
  <ItemGroup>
    <None Include="..\..\Images\Icon_64x64.png">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
    <None Include="..\..\LICENSE.txt">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Persistence\Waher.Persistence\Waher.Persistence.csproj" />
    <ProjectReference Include="..\..\Runtime\Waher.Runtime.Counters\Waher.Runtime.Counters.csproj" />
    <ProjectReference Include="..\..\Runtime\Waher.Runtime.Inventory\Waher.Runtime.Inventory.csproj" />
    <ProjectReference Include="..\..\Runtime\Waher.Runtime.Profiling\Waher.Runtime.Profiling.csproj" />
    <ProjectReference Include="..\..\Runtime\Waher.Runtime.Temporary\Waher.Runtime.Temporary.csproj" />
    <ProjectReference Include="..\Waher.Security\Waher.Security.csproj" />
  </ItemGroup>
</Project>
