using System;
using Waher.Networking.XMPP.Contracts;

namespace Waher.Mcp.Identity.Responses
{
	/// <summary>
	/// Identity attachment.
	/// </summary>
	public class IdentityAttachment
	{
		/// <summary>
		/// Identity attachment.
		/// </summary>
		/// <param name="Attachment">Identity attachment</param>
		public IdentityAttachment(Attachment Attachment)
		{
			this.Id = Attachment.Id;
			this.LegalId = Attachment.LegalId;
			this.ContentType = Attachment.ContentType;
			this.FileName = Attachment.FileName;
			this.Url = Attachment.Url;
			this.Signature = Attachment.Signature;
			this.Timestamp = Attachment.Timestamp;
		}

		/// <summary>
		/// Attachment ID
		/// </summary>
		public string Id;

		/// <summary>
		/// Legal ID of uploader of the attachment
		/// </summary>
		public string LegalId;

		/// <summary>
		/// Internet Content Type of binary attachment.
		/// </summary>
		public string ContentType;

		/// <summary>
		/// Filename of attachment.
		/// </summary>
		public string FileName;

		/// <summary>
		/// URL to retrieve attachment, if provided.
		/// </summary>
		public string Url;

		/// <summary>
		/// Binary signature of the attachment, generated by an approved legal identity of the account-holder.
		/// If no signature, attribute is null.
		/// </summary>
		public byte[] Signature;

		/// <summary>
		/// Timestamp of signature. If no signature, value is <see cref="DateTime.MinValue"/>
		/// </summary>
		public DateTime Timestamp;
	}
}
