using System;
using Waher.Mcp.Xmpp.Responses;
using Waher.Networking.HTTP.Mcp.Model.Attributes;
using Waher.Networking.XMPP.Contracts;

namespace Waher.Mcp.Identity.Responses
{
	/// <summary>
	/// Identity response.
	/// </summary>
	public class IdentityResponse : GenericResponse
	{
		/// <summary>
		/// Identity response.
		/// </summary>
		/// <param name="ErrorMessage">Error message.</param>
		public IdentityResponse(string ErrorMessage)
			: base(false, ErrorMessage)
		{
			this.Id = null;
			this.Provider = null;
			this.State = null;
			this.Created = null;
			this.Updated = null;
			this.From = null;
			this.To = null;
			this.Properties = null;
			this.Attachments = null;
			this.ClientKeyName = null;
			this.ClientPubKey = null;
			this.ClientSignature = null;
		}

		/// <summary>
		/// Identity response.
		/// </summary>
		/// <param name="Identity">Legal Identity object.</param>
		/// <param name="Message">Success message.</param>
		public IdentityResponse(LegalIdentity Identity, string Message)
			: base(true, Message)
		{
			int i, c;

			this.Id = Identity.Id;
			this.Provider = Identity.Provider;
			this.State = Identity.State;
			this.Created = Identity.Created;
			this.Updated = Identity.Updated;
			this.From = Identity.From;
			this.To = Identity.To;
			this.ClientKeyName = Identity.ClientKeyName;
			this.ClientPubKey = Identity.ClientPubKey;
			this.ClientSignature = Identity.ClientSignature;

			c = Identity.Properties.Length;
			this.Properties = new IdentityProperty[c];

			for (i = 0; i < c; i++)
				this.Properties[i] = new IdentityProperty(Identity.Properties[i]);

			c = Identity.Attachments.Length;
			this.Attachments = new IdentityAttachment[c];

			for (i = 0; i < c; i++)
				this.Attachments[i] = new IdentityAttachment(Identity.Attachments[i]);
		}

		/// <summary>
		/// Identifier of the identity.
		/// </summary>
		[McpStringParameter("Id", "Identifier of the identity.", 1, 128)]
		public string? Id;

		/// <summary>
		/// Trust Provider of the identity.
		/// </summary>
		[McpStringParameter("Provider", "Trust Provider of the identity.", 1, 128)]
		public string? Provider;

		/// <summary>
		/// State of the identity.
		/// </summary>
		[McpParameter("State", "State of the identity.")]
		[McpEnumValue(IdentityState.Created, "Created")]
		[McpEnumValue(IdentityState.Approved, "Approved")]
		[McpEnumValue(IdentityState.Rejected, "Rejected")]
		[McpEnumValue(IdentityState.Obsoleted, "Obsoleted")]
		[McpEnumValue(IdentityState.Compromised, "Compromised")]
		public IdentityState? State;

		/// <summary>
		/// Date and time when the identity was created.
		/// </summary>
		[McpDateTimeParameter("Created", "Date and time when the identity was created.")]
		public DateTime? Created;

		/// <summary>
		/// Date and time when the identity was last updated.
		/// </summary>
		[McpDateTimeParameter("Updated", "Date and time when the identity was last updated.")]
		public DateTime? Updated;

		/// <summary>
		/// Date when the identity becomes valid.
		/// </summary>
		[McpDateParameter("From", "Date when the identity becomes valid.")]
		public DateTime? From;

		/// <summary>
		/// Date when the identity becomes invalid.
		/// </summary>
		[McpDateParameter("To", "Date when the identity becomes invalid.")]
		public DateTime? To;

		/// <summary>
		/// Properties associated with the digital identity.
		/// </summary>
		[McpParameter("Properties", "Conceptual properties associated with the digital identity.")]
		public IdentityProperty[]? Properties;

		/// <summary>
		/// Attachments associated with the digital identity.
		/// </summary>
		[McpParameter("Attachments", "Attachments associated with the digital identity.")]
		public IdentityAttachment[]? Attachments;

		/// <summary>
		/// Name of the client key used to sign the request.
		/// </summary>
		[McpStringParameter("ClientKeyName", "Name of the client key used to sign the request.")]
		public string? ClientKeyName;

		/// <summary>
		/// Public key of the client, used to sign the request.
		/// </summary>
		[McpParameter("ClientPubKey", "Public key of the client, used to sign the request.")]
		public byte[]? ClientPubKey;

		/// <summary>
		/// Signature of the request, generated by the client.
		/// </summary>
		[McpParameter("ClientSignature", "Signature of the request, generated by the client.")]
		public byte[]? ClientSignature;
	}
}
