<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<AssemblyVersion>1.0.1</AssemblyVersion>
		<FileVersion>1.0.1</FileVersion>
		<Version>1.0.1</Version>
		<Authors>Peter Waher</Authors>
		<Company>Waher Data AB</Company>
		<Product>Waher.IoTGateway</Product>
		<Description>Provides an MCP Server for access to Internet Content. It contains tools for Getting, Posting, Putting, Deleting and Querying Internet resources, as well as encoding and decoding Internet Content.</Description>
		<Copyright>Copyright © Waher Data AB 2026. All rights reserved.</Copyright>
		<PackageProjectUrl>https://github.com/PeterWaher/IoTGateway/tree/master/Networking/Waher.Mcp.Content</PackageProjectUrl>
		<PackageIcon>Icon_64x64.png</PackageIcon>
		<RepositoryUrl>https://github.com/PeterWaher/IoTGateway</RepositoryUrl>
		<RepositoryType>GitHub</RepositoryType>
		<PackageTags>networking communication http MCP internet content</PackageTags>
	</PropertyGroup>
	<PropertyGroup>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\..\Images\Icon_64x64.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
    <ProjectReference Include="..\..\Networking\Waher.Networking.HTTP.Mcp\Waher.Networking.HTTP.Mcp.csproj" />
    <ProjectReference Include="..\..\Networking\Waher.Networking.HTTP.OAuth\Waher.Networking.HTTP.OAuth.csproj" />
    <ProjectReference Include="..\..\Networking\Waher.Networking.HTTP\Waher.Networking.HTTP.csproj" />
  </ItemGroup>

</Project>
