using System;
using System.Collections.Generic;
using System.Text;

namespace Waher.Networking.HTTP
{
	/// <summary>
	/// The requested resource MUST be accessed through the proxy given by the Location field. The Location field gives the URI of the proxy. 
	/// The recipient is expected to repeat this single request via the proxy. 305 responses MUST only be generated by origin servers.
	/// </summary>
	public class UseProxyException : HttpException
	{
		/// <summary>
		/// The requested resource MUST be accessed through the proxy given by the Location field. The Location field gives the URI of the proxy. 
		/// The recipient is expected to repeat this single request via the proxy. 305 responses MUST only be generated by origin servers.
		/// </summary>
		/// <param name="Location">Location.</param>
		public UseProxyException(string Location)
			: base(305, "Use Proxy", new KeyValuePair<string, string>("Location", Location))
		{
		}
	}
}
