using System;
using System.Collections.Generic;

namespace Waher.Networking.HTTP
{
	/// <summary>
	/// The requested resource MUST be accessed through the proxy given by the Location field. The Location field gives the URI of the proxy. 
	/// The recipient is expected to repeat this single request via the proxy. 305 responses MUST only be generated by origin servers.
	/// </summary>
	public class UseProxyException : HttpException
	{
		/// <summary>
		/// 305
		/// </summary>
		public const int Code = 305;

		/// <summary>
		/// Use Proxy
		/// </summary>
		public const string StatusMessage = "Use Proxy";

		/// <summary>
		/// The requested resource MUST be accessed through the proxy given by the Location field. The Location field gives the URI of the proxy. 
		/// The recipient is expected to repeat this single request via the proxy. 305 responses MUST only be generated by origin servers.
		/// </summary>
		/// <param name="Location">Location.</param>
		public UseProxyException(string Location)
			: base(Code, StatusMessage, new KeyValuePair<string, string>("Location", Location))
		{
		}

		/// <summary>
		/// The requested resource MUST be accessed through the proxy given by the Location field. The Location field gives the URI of the proxy. 
		/// The recipient is expected to repeat this single request via the proxy. 305 responses MUST only be generated by origin servers.
		/// </summary>
		/// <param name="Location">Location.</param>
		/// <param name="ContentObject">Any content object to return. The object will be encoded before being sent.</param>
		public UseProxyException(string Location, object ContentObject)
			: base(Code, StatusMessage, ContentObject, new KeyValuePair<string, string>("Location", Location))
		{
		}

		/// <summary>
		/// The requested resource MUST be accessed through the proxy given by the Location field. The Location field gives the URI of the proxy. 
		/// The recipient is expected to repeat this single request via the proxy. 305 responses MUST only be generated by origin servers.
		/// </summary>
		/// <param name="Location">Location.</param>
		/// <param name="Content">Any encoded content to return.</param>
		/// <param name="ContentType">The content type of <paramref name="Content"/>, if provided.</param>
		public UseProxyException(string Location, byte[] Content, string ContentType)
			: base(Code, StatusMessage, Content, ContentType, new KeyValuePair<string, string>("Location", Location))
		{
		}
	}
}
