function CreateInnerHTML(ElementId)
{
	var Element = document.getElementById(ElementId);
	if (Element)
		Element.innerHTML = CreateHtml();
}

function CreateHTML()
{
	var Segments = [
		"<p>",
		"Incomplete ",
		"<strong>",
		"strong",
		"</strong>",
		"</p>\r\n",
		"<p>",
		"Incomplete ",
		"<strong>",
		"strong",
		"*",
		"</strong>",
		"</p>\r\n",
		"<p>",
		"Incomplete ",
		"<em>",
		"emphasis",
		"</em>",
		"</p>\r\n",
		"<p>",
		"Incomplete ",
		"<u>",
		"underline",
		"</u>",
		"</p>\r\n",
		"<p>",
		"Incomplete ",
		"<ins>",
		"insertion",
		"</ins>",
		"</p>\r\n",
		"<p>",
		"Incomplete ",
		"<ins>",
		"insertion 2_",
		"</ins>",
		"</p>\r\n",
		"<p>",
		"Incomplete ",
		"<s>",
		"strike over",
		"</s>",
		"</p>\r\n",
		"<p>",
		"Incomplete ",
		"<del>",
		"deletion",
		"</del>",
		"</p>\r\n",
		"<p>",
		"Incomplete ",
		"<del>",
		"deletion 2~",
		"</del>",
		"</p>\r\n",
		"<p>",
		"Incomplete ",
		"<sup>",
		"superscript",
		"</sup>",
		"</p>\r\n",
		"<p>",
		"Incomplete ",
		"<sup>",
		"superscript 2",
		"</sup>",
		"</p>\r\n",
		"<p>",
		"Incomplete ",
		"[",
		"subscript",
		"</p>\r\n",
		"<p>",
		"Incomplete ",
		"<sub>",
		"link",
		"</sub>",
		"</p>\r\n",
		"<p>",
		"Incomplete ",
		"<a href=\"http://example.com",
		"\" target=\"_blank",
		"\">",
		"link 2",
		"</a>",
		"</p>\r\n",
		"<p>",
		"Incomplete ",
		"![",
		"media",
		"]",
		"</p>\r\n",
		"<p>",
		"Incomplete ",
		"<img src=\"http://example.com\" alt=\"media 2\"/>",
		"</p>\r\n",
		"<p>",
		"Incomplete ",
		"<code>code</code>",
		"</p>\r\n",
		"<pre><code class=\"",
		"nohighlight",
		"\">",
		"Incomplete code 2\r\n",
		"</code></pre>\r\n"];
	return Segments.join("");
}
