function CreateInnerHTML(ElementId, Args)
{
	var Element = document.getElementById(ElementId);
	if (Element)
		Element.innerHTML = CreateHTML(Args);
}

function CreateHTML(Args)
{
	var Segments = [
		"<table>\r\n",
		"<caption id=\"simple_table\">",
		"simple_table",
		"</caption>\r\n",
		"<colgroup>\r\n",
		"<col style=\"text-align:left\"/>\r\n",
		"<col style=\"text-align:center\"/>\r\n",
		"<col style=\"text-align:right\"/>\r\n",
		"</colgroup>\r\n",
		"<thead>\r\n",
		"<tr>\r\n",
		"<th style=\"text-align:left",
		"\">",
		"First Header",
		"</th>\r\n",
		"<th style=\"text-align:center",
		"\">",
		"Second Header",
		"</th>\r\n",
		"<th style=\"text-align:right",
		"\">",
		"Third Header",
		"</th>\r\n",
		"</tr>\r\n",
		"</thead>\r\n",
		"<tbody>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:left",
		"\">",
		"First row",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"Data",
		"</td>\r\n",
		"<td style=\"text-align:right",
		"\">",
		"Very long data entry",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:left",
		"\">",
		"Second row",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<strong>",
		"Cell",
		"</strong>",
		"</td>\r\n",
		"<td style=\"text-align:right",
		"\">",
		"<em>",
		"Cell",
		"</em>",
		"</td>\r\n",
		"</tr>\r\n",
		"</tbody>\r\n",
		"</table>\r\n",
		"<table>\r\n",
		"<caption id=\"reference_table\">",
		"Prototype table",
		"</caption>\r\n",
		"<colgroup>\r\n",
		"<col style=\"text-align:left\"/>\r\n",
		"<col style=\"text-align:center\"/>\r\n",
		"<col style=\"text-align:right\"/>\r\n",
		"</colgroup>\r\n",
		"<thead>\r\n",
		"<tr>\r\n",
		"<th style=\"text-align:left",
		"\">",
		"</th>\r\n",
		"<th style=\"text-align:center",
		"\" colspan=\"2",
		"\">",
		"Grouping",
		"</th>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<th style=\"text-align:left",
		"\">",
		"First Header",
		"</th>\r\n",
		"<th style=\"text-align:center",
		"\">",
		"Second Header",
		"</th>\r\n",
		"<th style=\"text-align:right",
		"\">",
		"Third Header",
		"</th>\r\n",
		"</tr>\r\n",
		"</thead>\r\n",
		"<tbody>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:left",
		"\">",
		"Content",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\" colspan=\"2",
		"\">",
		"<em>",
		"Long Cell",
		"</em>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:left",
		"\">",
		"Content",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<strong>",
		"Cell",
		"</strong>",
		"</td>\r\n",
		"<td style=\"text-align:right",
		"\">",
		"Cell",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:left",
		"\">",
		"New section",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"More",
		"</td>\r\n",
		"<td style=\"text-align:right",
		"\">",
		"Data",
		"</td>\r\n",
		"</tr>\r\n",
		"</tbody>\r\n",
		"</table>\r\n",
		"<table>\r\n",
		"<colgroup>\r\n",
		"<col style=\"text-align:left\"/>\r\n",
		"<col style=\"text-align:left\"/>\r\n",
		"</colgroup>\r\n",
		"<thead>\r\n",
		"<tr>\r\n",
		"<th style=\"text-align:left",
		"\" colspan=\"2",
		"\">",
		"Table with complex cells",
		"</th>\r\n",
		"</tr>\r\n",
		"</thead>\r\n",
		"<tbody>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:left",
		"\">",
		"<table>\r\n",
		"<colgroup>\r\n",
		"<col style=\"text-align:left\"/>\r\n",
		"<col style=\"text-align:right\"/>\r\n",
		"</colgroup>\r\n",
		"<thead>\r\n",
		"<tr>\r\n",
		"<th style=\"text-align:left",
		"\" colspan=\"2",
		"\">",
		"Info about cell",
		"</th>\r\n",
		"</tr>\r\n",
		"</thead>\r\n",
		"<tbody>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:left",
		"\">",
		"Row",
		"</td>\r\n",
		"<td style=\"text-align:right",
		"\">",
		"1",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:left",
		"\">",
		"Column",
		"</td>\r\n",
		"<td style=\"text-align:right",
		"\">",
		"1",
		"</td>\r\n",
		"</tr>\r\n",
		"</tbody>\r\n",
		"</table>\r\n",
		"</td>\r\n",
		"<td style=\"text-align:left",
		"\">",
		"<table>\r\n",
		"<colgroup>\r\n",
		"<col style=\"text-align:left\"/>\r\n",
		"<col style=\"text-align:right\"/>\r\n",
		"</colgroup>\r\n",
		"<thead>\r\n",
		"<tr>\r\n",
		"<th style=\"text-align:left",
		"\" colspan=\"2",
		"\">",
		"Info about cell",
		"</th>\r\n",
		"</tr>\r\n",
		"</thead>\r\n",
		"<tbody>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:left",
		"\">",
		"Row",
		"</td>\r\n",
		"<td style=\"text-align:right",
		"\">",
		"1",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:left",
		"\">",
		"Column",
		"</td>\r\n",
		"<td style=\"text-align:right",
		"\">",
		"2",
		"</td>\r\n",
		"</tr>\r\n",
		"</tbody>\r\n",
		"</table>\r\n",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:left",
		"\">",
		"<table>\r\n",
		"<colgroup>\r\n",
		"<col style=\"text-align:left\"/>\r\n",
		"<col style=\"text-align:right\"/>\r\n",
		"</colgroup>\r\n",
		"<thead>\r\n",
		"<tr>\r\n",
		"<th style=\"text-align:left",
		"\" colspan=\"2",
		"\">",
		"Info about cell",
		"</th>\r\n",
		"</tr>\r\n",
		"</thead>\r\n",
		"<tbody>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:left",
		"\">",
		"Row",
		"</td>\r\n",
		"<td style=\"text-align:right",
		"\">",
		"2",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:left",
		"\">",
		"Column",
		"</td>\r\n",
		"<td style=\"text-align:right",
		"\">",
		"1",
		"</td>\r\n",
		"</tr>\r\n",
		"</tbody>\r\n",
		"</table>\r\n",
		"</td>\r\n",
		"<td style=\"text-align:left",
		"\">",
		"<table>\r\n",
		"<colgroup>\r\n",
		"<col style=\"text-align:left\"/>\r\n",
		"<col style=\"text-align:right\"/>\r\n",
		"</colgroup>\r\n",
		"<thead>\r\n",
		"<tr>\r\n",
		"<th style=\"text-align:left",
		"\" colspan=\"2",
		"\">",
		"Info about cell",
		"</th>\r\n",
		"</tr>\r\n",
		"</thead>\r\n",
		"<tbody>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:left",
		"\">",
		"Row",
		"</td>\r\n",
		"<td style=\"text-align:right",
		"\">",
		"2",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:left",
		"\">",
		"Column",
		"</td>\r\n",
		"<td style=\"text-align:right",
		"\">",
		"2",
		"</td>\r\n",
		"</tr>\r\n",
		"</tbody>\r\n",
		"</table>\r\n",
		"</td>\r\n",
		"</tr>\r\n",
		"</tbody>\r\n",
		"</table>\r\n",
		"<table>\r\n",
		"<colgroup>\r\n",
		"<col style=\"text-align:left\"/>\r\n",
		"<col style=\"text-align:left\"/>\r\n",
		"</colgroup>\r\n",
		"<thead>\r\n",
		"<tr>\r\n",
		"<th style=\"text-align:left",
		"\" colspan=\"2",
		"\">",
		"</th>\r\n",
		"</tr>\r\n",
		"</thead>\r\n",
		"<tbody>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:left",
		"\">",
		"e",
		"<sub>",
		"1,1",
		"</sub>",
		"</td>\r\n",
		"<td style=\"text-align:left",
		"\">",
		"e",
		"<sub>",
		"1,2",
		"</sub>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:left",
		"\">",
		"e",
		"<sub>",
		"2,1",
		"</sub>",
		"</td>\r\n",
		"<td style=\"text-align:left",
		"\">",
		"e",
		"<sub>",
		"2,2",
		"</sub>",
		"</td>\r\n",
		"</tr>\r\n",
		"</tbody>\r\n",
		"</table>\r\n",
		"<table>\r\n",
		"<colgroup>\r\n",
		"<col style=\"text-align:left\"/>\r\n",
		"</colgroup>\r\n",
		"<thead>\r\n",
		"<tr>\r\n",
		"<th style=\"text-align:left",
		"\">",
		"One-column table",
		"</th>\r\n",
		"</tr>\r\n",
		"</thead>\r\n",
		"<tbody>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:left",
		"\">",
		"Row 1",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:left",
		"\">",
		"Row 2",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:left",
		"\">",
		"Row 3",
		"</td>\r\n",
		"</tr>\r\n",
		"</tbody>\r\n",
		"</table>\r\n",
		"<table>\r\n",
		"<colgroup>\r\n",
		"<col style=\"text-align:left\"/>\r\n",
		"<col style=\"text-align:center\"/>\r\n",
		"<col style=\"text-align:left\"/>\r\n",
		"</colgroup>\r\n",
		"<thead>\r\n",
		"</thead>\r\n",
		"<tbody>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:left",
		"\">",
		"No",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"headers",
		"</td>\r\n",
		"<td style=\"text-align:left",
		"\">",
		"table",
		"</td>\r\n",
		"</tr>\r\n",
		"</tbody>\r\n",
		"</table>\r\n",
		"<table>\r\n",
		"<colgroup>\r\n",
		"<col style=\"text-align:left\"/>\r\n",
		"<col style=\"text-align:center\"/>\r\n",
		"<col style=\"text-align:right\"/>\r\n",
		"</colgroup>\r\n",
		"<thead>\r\n",
		"<tr>\r\n",
		"<th style=\"text-align:left",
		"\" colspan=\"3",
		"\">",
		"Cell alignment table",
		"</th>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<th style=\"text-align:left",
		"\">",
		"Left",
		"</th>\r\n",
		"<th style=\"text-align:center",
		"\">",
		"Center",
		"</th>\r\n",
		"<th style=\"text-align:right",
		"\">",
		"Right",
		"</th>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<th style=\"text-align:left",
		"\">",
		"Left",
		"</th>\r\n",
		"<th style=\"text-align:left",
		"\">",
		"Left",
		"</th>\r\n",
		"<th style=\"text-align:left",
		"\">",
		"Left",
		"</th>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<th style=\"text-align:right",
		"\">",
		"Right",
		"</th>\r\n",
		"<th style=\"text-align:right",
		"\">",
		"Right",
		"</th>\r\n",
		"<th style=\"text-align:right",
		"\">",
		"Right",
		"</th>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<th style=\"text-align:center",
		"\">",
		"Center",
		"</th>\r\n",
		"<th style=\"text-align:center",
		"\">",
		"Center",
		"</th>\r\n",
		"<th style=\"text-align:center",
		"\">",
		"Center",
		"</th>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<th style=\"text-align:center",
		"\">",
		"Justified",
		"</th>\r\n",
		"<th style=\"text-align:center",
		"\">",
		"Justified",
		"</th>\r\n",
		"<th style=\"text-align:center",
		"\">",
		"Justified",
		"</th>\r\n",
		"</tr>\r\n",
		"</thead>\r\n",
		"<tbody>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:left",
		"\">",
		"Normal",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"Normal",
		"</td>\r\n",
		"<td style=\"text-align:right",
		"\">",
		"Normal",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:left",
		"\">",
		"Left",
		"</td>\r\n",
		"<td style=\"text-align:left",
		"\">",
		"Left",
		"</td>\r\n",
		"<td style=\"text-align:left",
		"\">",
		"Left",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:right",
		"\">",
		"Right",
		"</td>\r\n",
		"<td style=\"text-align:right",
		"\">",
		"Right",
		"</td>\r\n",
		"<td style=\"text-align:right",
		"\">",
		"Right",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"Center",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"Center",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"Center",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"Justified",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"Justified",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"Justified",
		"</td>\r\n",
		"</tr>\r\n",
		"</tbody>\r\n",
		"</table>\r\n"];
	return Segments.join("");
}
