function CreateInnerHTML(ElementId)
{
	var Element = document.getElementById(ElementId);
	if (Element)
		Element.innerHTML = CreateHTML();
}

function CreateHTML()
{
	var Segments = [
		"<dl>\r\n",
		"<dt>",
		"Apple",
		"</dt>\r\n",
		"<dd>",
		"Pomaceous fruit of plants of the genus Malus in the family Rosaceae.",
		"</dd>\r\n",
		"<dt>",
		"Orange",
		"</dt>\r\n",
		"<dd>",
		"The fruit of an evergreen tree of the genus Citrus.",
		"</dd>\r\n",
		"</dl>\r\n",
		"<hr/>\r\n",
		"<dl>\r\n",
		"<dt>",
		"Apple",
		"</dt>\r\n",
		"<dd>",
		"Pomaceous fruit of plants of the genus Malus in the family Rosaceae.",
		"</dd>\r\n",
		"<dt>",
		"Orange",
		"</dt>\r\n",
		"<dd>",
		"The fruit of an evergreen tree of the genus Citrus.",
		"</dd>\r\n",
		"</dl>\r\n",
		"<hr/>\r\n",
		"<dl>\r\n",
		"<dt>",
		"Apple",
		"</dt>\r\n",
		"<dd>",
		"Pomaceous fruit of plants of the genus Malus in the family Rosaceae.",
		"</dd>\r\n",
		"<dd>",
		"An American computer company.",
		"</dd>\r\n",
		"<dt>",
		"Orange",
		"</dt>\r\n",
		"<dd>",
		"The fruit of an evergreen tree of the genus Citrus.",
		"</dd>\r\n",
		"</dl>\r\n",
		"<hr/>\r\n",
		"<dl>\r\n",
		"<dt>",
		"Term 1",
		"</dt>\r\n",
		"<dt>",
		"Term 2",
		"</dt>\r\n",
		"<dd>",
		"Definition a",
		"</dd>\r\n",
		"<dt>",
		"Term 3",
		"</dt>\r\n",
		"<dd>",
		"Definition b",
		"</dd>\r\n",
		"</dl>\r\n",
		"<hr/>\r\n",
		"<dl>\r\n",
		"<dt>",
		"Apple",
		"</dt>\r\n",
		"<dd>",
		"<p>",
		"Pomaceous fruit of plants of the genus Malus in the family Rosaceae.",
		"</p>\r\n",
		"</dd>\r\n",
		"<dt>",
		"Orange",
		"</dt>\r\n",
		"<dd>",
		"<p>",
		"The fruit of an evergreen tree of the genus Citrus.",
		"</p>\r\n",
		"</dd>\r\n",
		"</dl>\r\n",
		"<hr/>\r\n",
		"<dl>\r\n",
		"<dt>",
		"Term 1",
		"</dt>\r\n",
		"<dd>",
		"<p>",
		"This is a definition with two paragraphs. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam hendrerit mi posuere lectus.",
		"</p>\r\n",
		"<p>",
		"Vestibulum enim wisi, viverra nec, fringilla in, laoreet vitae, risus.",
		"</p>\r\n",
		"</dd>\r\n",
		"<dd>",
		"<p>",
		"Second definition for term 1, also wrapped in a paragraph because of the blank line preceding it.",
		"</p>\r\n",
		"</dd>\r\n",
		"<dt>",
		"Term 2",
		"</dt>\r\n",
		"<dd>",
		"<p>",
		"This definition has a code block, a blockquote and a list.",
		"</p>\r\n",
		"<pre><code class=\"",
		"nohighlight",
		"\">",
		"code block.\r\n",
		"</code></pre>\r\n",
		"<blockquote>\r\n",
		"<p>",
		"block quote on two lines.",
		"</p>\r\n",
		"</blockquote>\r\n",
		"<ol>\r\n",
		"<li>",
		"first list item",
		"</li>\r\n",
		"<li>",
		"second list item",
		"</li>\r\n",
		"</ol>\r\n",
		"</dd>\r\n",
		"</dl>\r\n"];
	return Segments.join("");
}
