function CreateInnerHTML(ElementId)
{
	var Element = document.getElementById(ElementId);
	if (Element)
		Element.innerHTML = CreateHtml();
}

function CreateHTML()
{
	var Segments = [
		"<h2",
		" id=\"tablesNotes\"",
		">",
		"Tables &amp; Notes",
		"</h2>\r\n",
		"<p>",
		"This example mixes footnotes",
		"<sup id=\"fnref-1\"><a href=\"#fn-1\" class=\"footnote-ref\">1</a></sup>",
		" and tables.",
		"</p>\r\n",
		"<h3",
		" id=\"tableWithLargeCells\"",
		">",
		"Table with large cells",
		"</h3>\r\n",
		"<table>\r\n",
		"<colgroup>\r\n",
		"<col style=\"text-align:left\"/>\r\n",
		"<col style=\"text-align:left\"/>\r\n",
		"</colgroup>\r\n",
		"<thead>\r\n",
		"<tr>\r\n",
		"<th style=\"text-align:left",
		"\" colspan=\"2",
		"\">",
		"&nbsp;",
		"</th>\r\n",
		"</tr>\r\n",
		"</thead>\r\n",
		"<tbody>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:left",
		"\">",
		"<p>",
		"First cell, first row",
		"</p>\r\n",
		"<p>",
		"First cell, second row",
		"</p>\r\n",
		"<p>",
		"First cell, third row",
		"</p>\r\n",
		"</td>\r\n",
		"<td style=\"text-align:left",
		"\">",
		"<p>",
		"Second cell, first row",
		"</p>\r\n",
		"<p>",
		"Second cell, second row",
		"</p>\r\n",
		"<p>",
		"Second cell, third row",
		"</p>\r\n",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:left",
		"\">",
		"<p>",
		"Third cell, first row",
		"</p>\r\n",
		"<p>",
		"Third cell, second row",
		"</p>\r\n",
		"<p>",
		"Third cell, third row",
		"</p>\r\n",
		"</td>\r\n",
		"<td style=\"text-align:left",
		"\">",
		"<p>",
		"Fourth cell, first row",
		"</p>\r\n",
		"<p>",
		"Fourth cell, second row",
		"</p>\r\n",
		"<p>",
		"Fourth cell, third row",
		"</p>\r\n",
		"</td>\r\n",
		"</tr>\r\n",
		"</tbody>\r\n",
		"</table>\r\n",
		"<p>",
		"The purpose is to see if footnotes",
		"<sup id=\"fnref-2\"><a href=\"#fn-2\" class=\"footnote-ref\">2</a></sup>",
		" and tables with complex cells interfere with each other.",
		"</p>\r\n",
		"<div class=\"footnotes\">\r\n",
		"<hr />\r\n",
		"<ol>\r\n",
		"<li id=\"fn-1\">",
		"<p>",
		"Like this one, presented ",
		"<strong>",
		"<u>",
		"before",
		"</u>",
		"</strong>",
		" the table.",
		"<a href=\"#fnref-1\" class=\"footnote-backref\">&#8617;</a>",
		"</p>\r\n",
		"</li>\r\n",
		"<li id=\"fn-2\">",
		"<p>",
		"Like this one, presented ",
		"<strong>",
		"<u>",
		"after",
		"</u>",
		"</strong>",
		" the table.",
		"<a href=\"#fnref-2\" class=\"footnote-backref\">&#8617;</a>",
		"</p>\r\n",
		"</li>\r\n",
		"</ol>\r\n",
		"</div>\r\n"];
	return Segments.join("");
}
