function CreateInnerHTML(ElementId, Args)
{
	var Element = document.getElementById(ElementId);
	if (Element)
		Element.innerHTML = CreateHTML(Args);
}

function CreateHTML(Args)
{
	var Segments = [
		"<p>",
		"Markdown uses email-style &gt; characters for blockquoting. If you’re familiar with quoting passages of text in an email message, then you know how to create a blockquote in Markdown. It looks best if you hard wrap the text and put a &gt; before every line:",
		"</p>\r\n",
		"<blockquote>\r\n",
		"<p>",
		"This is a blockquote with two paragraphs. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam hendrerit mi posuere lectus. Vestibulum enim wisi, viverra nec, fringilla in, laoreet vitae, risus.",
		"</p>\r\n",
		"<p>",
		"Donec sit amet nisl. Aliquam semper ipsum sit amet velit. Suspendisse id sem consectetuer libero luctus adipiscing.",
		"</p>\r\n",
		"</blockquote>\r\n",
		"<p>",
		"Markdown allows you to be lazy and only put the &gt; before the first line of a hard-wrapped paragraph:",
		"</p>\r\n",
		"<blockquote>\r\n",
		"<p>",
		"This is a blockquote with two paragraphs. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam hendrerit mi posuere lectus. Vestibulum enim wisi, viverra nec, fringilla in, laoreet vitae, risus.",
		"</p>\r\n",
		"<p>",
		"Donec sit amet nisl. Aliquam semper ipsum sit amet velit. Suspendisse id sem consectetuer libero luctus adipiscing.",
		"</p>\r\n",
		"</blockquote>\r\n",
		"<p>",
		"Blockquotes can be nested (i.e. a blockquote-in-a-blockquote) by adding additional levels of &gt;:",
		"</p>\r\n",
		"<blockquote>\r\n",
		"<p>",
		"This is the first level of quoting.",
		"</p>\r\n",
		"<blockquote>\r\n",
		"<p>",
		"This is nested blockquote.",
		"</p>\r\n",
		"</blockquote>\r\n",
		"<p>",
		"Back to the first level.",
		"</p>\r\n",
		"</blockquote>\r\n",
		"<p>",
		"Blockquotes can contain other Markdown elements, including headers, lists, and code blocks:",
		"</p>\r\n",
		"<blockquote>\r\n",
		"<h2",
		" id=\"thisIsAHeader\"",
		">",
		"This is a header.",
		"</h2>\r\n",
		"<ol>\r\n",
		"<li>",
		"This is the first list item.",
		"</li>\r\n",
		"<li>",
		"This is the second list item.",
		"</li>\r\n",
		"</ol>\r\n",
		"<p>",
		"Here",
		"&rsquo;",
		"s some example code:",
		"</p>\r\n",
		"<pre><code class=\"",
		"nohighlight",
		"\">",
		"return shell_exec(\"echo $input | $markdown_script\");\r\n",
		"</code></pre>\r\n",
		"</blockquote>\r\n",
		"<p>",
		"Blockquotes can also be used do illustrate editing:",
		"</p>\r\n",
		"<blockquote class=\"inserted\">\r\n",
		"<p>",
		"This paragraph has been inserted",
		"</p>\r\n",
		"</blockquote>\r\n",
		"<blockquote class=\"deleted\">\r\n",
		"<p>",
		"While this paragraph has been deleted",
		"</p>\r\n",
		"</blockquote>\r\n"];
	return Segments.join("");
}
