function CreateInnerHTML(ElementId, Args)
{
	var Element = document.getElementById(ElementId);
	if (Element)
		Element.innerHTML = CreateHTML(Args);
}

function CreateHTML(Args)
{
	var Segments = [
		"<p>",
		"Lazy numbering can be accomplished by prefixing items with ",
		"<code>#.</code>",
		":",
		"</p>\r\n",
		"<ol>\r\n",
		"<li>",
		"Bird",
		"</li>\r\n",
		"<li>",
		"McHale",
		"</li>\r\n",
		"<li>",
		"Parish",
		"</li>\r\n",
		"</ol>\r\n",
		"<p>",
		"To make lists look nice, you can wrap items with hanging indents:",
		"</p>\r\n",
		"<ol>\r\n",
		"<li>",
		"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam hendrerit mi posuere lectus. Vestibulum enim wisi, viverra nec, fringilla in, laoreet vitae, risus.",
		"</li>\r\n",
		"<li>",
		"Donec sit amet nisl. Aliquam semper ipsum sit amet velit. Suspendisse id sem consectetuer libero luctus adipiscing.",
		"</li>\r\n",
		"</ol>\r\n",
		"<p>",
		"But if you want to be lazy, you don’t have to:",
		"</p>\r\n",
		"<ol>\r\n",
		"<li>",
		"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam hendrerit mi posuere lectus. Vestibulum enim wisi, viverra nec, fringilla in, laoreet vitae, risus.",
		"</li>\r\n",
		"<li>",
		"Donec sit amet nisl. Aliquam semper ipsum sit amet velit. Suspendisse id sem consectetuer libero luctus adipiscing.",
		"</li>\r\n",
		"</ol>\r\n",
		"<p>",
		"On separate lines:",
		"</p>\r\n",
		"<ol>\r\n",
		"<li>",
		"<p>",
		"Bird",
		"</p>\r\n",
		"</li>\r\n",
		"<li>",
		"<p>",
		"Magic",
		"</p>\r\n",
		"</li>\r\n",
		"</ol>\r\n",
		"<p>",
		"List items may consist of multiple paragraphs. Each subsequent paragraph in a list item must be indented by either 4 spaces or one tab:",
		"</p>\r\n",
		"<ol>\r\n",
		"<li>",
		"<p>",
		"This is a list item with two paragraphs. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam hendrerit mi posuere lectus.",
		"</p>\r\n",
		"<p>",
		"Vestibulum enim wisi, viverra nec, fringilla in, laoreet vitae, risus. Donec sit amet nisl. Aliquam semper ipsum sit amet velit.",
		"</p>\r\n",
		"</li>\r\n",
		"<li>",
		"<p>",
		"Suspendisse id sem consectetuer libero luctus adipiscing.",
		"</p>\r\n",
		"</li>\r\n",
		"</ol>\r\n",
		"<p>",
		"It looks nice if you indent every line of the subsequent paragraphs, but here again, Markdown will allow you to be lazy:",
		"</p>\r\n",
		"<ol>\r\n",
		"<li>",
		"<p>",
		"This is a list item with two paragraphs.",
		"</p>\r\n",
		"<p>",
		"This is the second paragraph in the list item. You",
		"&rsquo;",
		"re only required to indent the first line. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
		"</p>\r\n",
		"</li>\r\n",
		"<li>",
		"<p>",
		"Another item in the same list.",
		"</p>\r\n",
		"</li>\r\n",
		"</ol>\r\n",
		"<p>",
		"To put a blockquote within a list item, the blockquote’s &gt; delimiters need to be indented:",
		"</p>\r\n",
		"<ol>\r\n",
		"<li>",
		"<p>",
		"A list item with a blockquote:",
		"</p>\r\n",
		"<blockquote>\r\n",
		"<p>",
		"This is a blockquote inside a list item.",
		"</p>\r\n",
		"</blockquote>\r\n",
		"</li>\r\n",
		"</ol>\r\n",
		"<p>",
		"To put a code block within a list item, the code block needs to be indented twice — 8 spaces or two tabs:",
		"</p>\r\n",
		"<ol>\r\n",
		"<li>",
		"<p>",
		"A list item with a code block:",
		"</p>\r\n",
		"<pre><code class=\"",
		"nohighlight",
		"\">",
		"[code goes here]\r\n",
		"</code></pre>\r\n",
		"</li>\r\n",
		"</ol>\r\n",
		"<p>",
		"Nested lists:",
		"</p>\r\n",
		"<ol>\r\n",
		"<li>",
		"Item 1",
		"</li>\r\n",
		"<li>",
		"Item 2 ",
		"<ul>\r\n",
		"<li",
		">",
		"Item 2a",
		"</li>\r\n",
		"<li",
		">",
		"Item 2b",
		"</li>\r\n",
		"</ul>\r\n",
		"</li>\r\n",
		"</ol>\r\n",
		"<p>",
		"Nested lists 2:",
		"</p>\r\n",
		"<ol>\r\n",
		"<li>",
		"Item 1",
		"</li>\r\n",
		"<li>",
		"Item 2 ",
		"<ol>\r\n",
		"<li>",
		"Item 2a",
		"</li>\r\n",
		"<li>",
		"Item 2b",
		"</li>\r\n",
		"</ol>\r\n",
		"</li>\r\n",
		"</ol>\r\n",
		"<p>",
		"Nested lists 3:",
		"</p>\r\n",
		"<ol>\r\n",
		"<li>",
		"Item 1",
		"</li>\r\n",
		"<li>",
		"Item 2 ",
		"<ol>\r\n",
		"<li value=\"2\">",
		"Item 2a",
		"</li>\r\n",
		"<li>",
		"Item 2b",
		"</li>\r\n",
		"</ol>\r\n",
		"</li>\r\n",
		"</ol>\r\n",
		"<p>",
		"Three levels:",
		"</p>\r\n",
		"<ol>\r\n",
		"<li>",
		"Item 1",
		"</li>\r\n",
		"<li>",
		"Item 2 ",
		"<ol>\r\n",
		"<li>",
		"Item 2a",
		"</li>\r\n",
		"<li>",
		"Item 2b ",
		"<ol>\r\n",
		"<li>",
		"Item 2bi",
		"</li>\r\n",
		"<li>",
		"Item 2bii",
		"</li>\r\n",
		"<li>",
		"Item 2biii",
		"</li>\r\n",
		"</ol>\r\n",
		"</li>\r\n",
		"<li>",
		"Item 2c",
		"</li>\r\n",
		"</ol>\r\n",
		"</li>\r\n",
		"<li>",
		"Item 3",
		"</li>\r\n",
		"</ol>\r\n",
		"<p>",
		"Multi-paragraph, multi-level lists:",
		"</p>\r\n",
		"<ol>\r\n",
		"<li>",
		"<p>",
		"Item 1",
		"</p>\r\n",
		"<p>",
		"Second paragraph of item 1.",
		"</p>\r\n",
		"<pre><code class=\"",
		"nohighlight",
		"\">",
		"This is some code of item 1.\r\n",
		"</code></pre>\r\n",
		"<p>",
		"Third paragraph of item 1.",
		"</p>\r\n",
		"<ol>\r\n",
		"<li>",
		"<p>",
		"Item 1.1",
		"</p>\r\n",
		"<p>",
		"Second paragraph of item 1.1.",
		"</p>\r\n",
		"<pre><code class=\"",
		"nohighlight",
		"\">",
		"This is some code of item 1.1.\r\n",
		"</code></pre>\r\n",
		"<p>",
		"Third paragraph of item 1.1.",
		"</p>\r\n",
		"<ol>\r\n",
		"<li>",
		"<p>",
		"Item 1.1.1",
		"</p>\r\n",
		"<p>",
		"Second paragraph of item 1.1.1.",
		"</p>\r\n",
		"<pre><code class=\"",
		"nohighlight",
		"\">",
		"This is some code of item 1.1.1.\r\n",
		"</code></pre>\r\n",
		"<p>",
		"Third paragraph of item 1.1.1.",
		"</p>\r\n",
		"</li>\r\n",
		"<li>",
		"<p>",
		"Item 1.1.2",
		"</p>\r\n",
		"<p>",
		"Second paragraph of item 1.1.2.",
		"</p>\r\n",
		"<pre><code class=\"",
		"nohighlight",
		"\">",
		"This is some code of item 1.1.2.\r\n",
		"</code></pre>\r\n",
		"<p>",
		"Third paragraph of item 1.1.2.",
		"</p>\r\n",
		"</li>\r\n",
		"</ol>\r\n",
		"</li>\r\n",
		"<li>",
		"<p>",
		"Item 1.2",
		"</p>\r\n",
		"<p>",
		"Second paragraph of item 1.2.",
		"</p>\r\n",
		"<pre><code class=\"",
		"nohighlight",
		"\">",
		"This is some code of item 1.2.\r\n",
		"</code></pre>\r\n",
		"<p>",
		"Third paragraph of item 1.2.",
		"</p>\r\n",
		"<ol>\r\n",
		"<li>",
		"<p>",
		"Item 1.2.1",
		"</p>\r\n",
		"<p>",
		"Second paragraph of item 1.2.1.",
		"</p>\r\n",
		"<pre><code class=\"",
		"nohighlight",
		"\">",
		"This is some code of item 1.2.1.\r\n",
		"</code></pre>\r\n",
		"<p>",
		"Third paragraph of item 1.2.1.",
		"</p>\r\n",
		"</li>\r\n",
		"<li>",
		"<p>",
		"Item 1.2.2",
		"</p>\r\n",
		"<p>",
		"Second paragraph of item 1.2.2.",
		"</p>\r\n",
		"<pre><code class=\"",
		"nohighlight",
		"\">",
		"This is some code of item 1.2.2.\r\n",
		"</code></pre>\r\n",
		"<p>",
		"Third paragraph of item 1.2.2.",
		"</p>\r\n",
		"</li>\r\n",
		"</ol>\r\n",
		"</li>\r\n",
		"</ol>\r\n",
		"</li>\r\n",
		"</ol>\r\n",
		"<p>",
		"Starting with simple items, continuing with block items:",
		"</p>\r\n",
		"<ol>\r\n",
		"<li>",
		"Item 1.",
		"</li>\r\n",
		"<li>",
		"Item 2.",
		"</li>\r\n",
		"<li>",
		"Item 3.",
		"</li>\r\n",
		"<li>",
		"Item 4.",
		"<p>",
		"Item 4 has a second paragraph.",
		"</p>\r\n",
		"</li>\r\n",
		"<li>",
		"Item 5.",
		"</li>\r\n",
		"<li>",
		"Item 6.",
		"</li>\r\n",
		"</ol>\r\n",
		"<p>",
		"Multi-paragraph, multi-level lists:",
		"</p>\r\n",
		"<ol>\r\n",
		"<li>",
		"<p>",
		"Unchecked",
		"</p>\r\n",
		"<p>",
		"Second paragraph of item 1",
		"</p>\r\n",
		"</li>\r\n",
		"<li>",
		"<p>",
		"Checked",
		"</p>\r\n",
		"<p>",
		"Second paragraph of item 2",
		"</p>\r\n",
		"<ol>\r\n",
		"<li>",
		"<p>",
		"Unchecked subitem",
		"</p>\r\n",
		"<pre><code class=\"",
		"nohighlight",
		"\">",
		"Some code\r\n",
		"</code></pre>\r\n",
		"<p>",
		"Second paragraph of item 2.1",
		"</p>\r\n",
		"</li>\r\n",
		"<li>",
		"<p>",
		"Checked subitem",
		"</p>\r\n",
		"<p>",
		"Second paragraph of item 2.2",
		"</p>\r\n",
		"<ol>\r\n",
		"<li>",
		"Unchecked subsubitem",
		"</li>\r\n",
		"<li>",
		"Checked subsubitem",
		"<pre><code class=\"",
		"nohighlight",
		"\">",
		"Some code\r\n",
		"</code></pre>\r\n",
		"<p>",
		"Second paragraph of item 2.2.2",
		"</p>\r\n",
		"</li>\r\n",
		"<li>",
		"Second checked subsubitem",
		"</li>\r\n",
		"<li>",
		"Second unchecked subsubitem",
		"</li>\r\n",
		"</ol>\r\n",
		"</li>\r\n",
		"<li>",
		"<p>",
		"Second checked subitem",
		"</p>\r\n",
		"<p>",
		"Second paragraph of item 2.3",
		"</p>\r\n",
		"</li>\r\n",
		"<li>",
		"<p>",
		"Second unchecked subitem",
		"</p>\r\n",
		"<p>",
		"Second paragraph of item 2.4",
		"</p>\r\n",
		"</li>\r\n",
		"</ol>\r\n",
		"</li>\r\n",
		"<li>",
		"<p>",
		"Also checked",
		"</p>\r\n",
		"<p>",
		"Second paragraph of item 3",
		"</p>\r\n",
		"</li>\r\n",
		"</ol>\r\n",
		"<p>",
		"Nested indentation:",
		"</p>\r\n",
		"<ol>\r\n",
		"<li>",
		"<ol>\r\n",
		"<li>",
		"<p>",
		"Header 1",
		"</p>\r\n",
		"<ol>\r\n",
		"<li>",
		"Header 1.1",
		"</li>\r\n",
		"<li>",
		"Header 1.2",
		"</li>\r\n",
		"<li>",
		"Header 1.3",
		"</li>\r\n",
		"<li>",
		"Header 1.4",
		"</li>\r\n",
		"</ol>\r\n",
		"</li>\r\n",
		"</ol>\r\n",
		"<ol>\r\n",
		"<li>",
		"<p>",
		"Header 2",
		"</p>\r\n",
		"<ol>\r\n",
		"<li>",
		"Header 2.1",
		"</li>\r\n",
		"<li>",
		"Header 2.2",
		"</li>\r\n",
		"<li>",
		"Header 2.3",
		"</li>\r\n",
		"</ol>\r\n",
		"</li>\r\n",
		"</ol>\r\n",
		"</li>\r\n",
		"</ol>\r\n"];
	return Segments.join("");
}
