function CreateInnerHTML(ElementId)
{
	var Element = document.getElementById(ElementId);
	if (Element)
		Element.innerHTML = CreateHTML();
}

function CreateHTML()
{
	var Segments = [
		"<p>",
		"This is a normal paragraph:",
		"</p>\r\n",
		"<pre><code class=\"",
		"nohighlight",
		"\">",
		"This is a code block.\r\n",
		"</code></pre>\r\n",
		"<p>",
		"Here is an example of AppleScript:",
		"</p>\r\n",
		"<pre><code class=\"",
		"nohighlight",
		"\">",
		"tell application \"Foo\"\r\n",
		"    beep\r\n",
		"end tell\r\n",
		"</code></pre>\r\n",
		"<p>",
		"Fenced code block:",
		"</p>\r\n",
		"<pre><code class=\"",
		"nohighlight",
		"\">",
		"&lt;div class=\"footer\"&gt;\r\n",
		"    &amp;copy; 2004 Foo Corporation\r\n",
		"&lt;/div&gt;\r\n",
		"</code></pre>\r\n",
		"<p>",
		"Fenced code block (with syntax highlighting):",
		"</p>\r\n",
		"<pre><code class=\"",
		"basic",
		"\">",
		"\r\n",
		"10 PRINT \"*\";\r\n",
		"\r\n",
		"20 GOTO 10\r\n",
		"\r\n",
		"</code></pre>\r\n",
		"<p>",
		"Headers can also be written on a single line, prefixing them with hash signs (",
		"<code>#</code>",
		") and a space character. The number of hash signs defines the level of the header:",
		"</p>\r\n",
		"<pre><code class=\"",
		"nohighlight",
		"\">",
		"# First level header\r\n",
		"\r\n",
		"## Second level header\r\n",
		"\r\n",
		"### Third level header\r\n",
		"\r\n",
		"#### Fourth level header\r\n",
		"\r\n",
		"...\r\n",
		"</code></pre>\r\n",
		"<pre><code class=\"",
		"nohighlight",
		"\">",
		"```\r\n",
		"&lt;div class=\"footer\"&gt;\r\n",
		"    &amp;copy; 2004 Foo Corporation\r\n",
		"&lt;/div&gt;\r\n",
		"```\r\n",
		"</code></pre>\r\n"];
	return Segments.join("");
}
