function CreateInnerHTML(ElementId)
{
	var Element = document.getElementById(ElementId);
	if (Element)
		Element.innerHTML = CreateHtml();
}

function CreateHTML()
{
	var Segments = [
		"<p>",
		"This is ",
		"<a href=\"http://example.com/",
		"\" title=\"Title",
		"\" target=\"_blank",
		"\">",
		"an example",
		"</a>",
		" inline link.",
		"</p>\r\n",
		"<p>",
		"<a href=\"http://example.net/",
		"\" target=\"_blank",
		"\">",
		"This link",
		"</a>",
		" has no title attribute.",
		"</p>\r\n",
		"<p>",
		"See my ",
		"<a href=\"/about/",
		"\">",
		"About",
		"</a>",
		" page for details.",
		"</p>\r\n",
		"<p>",
		"This is ",
		"<a href=\"http://example.com/",
		"\" title=\"Optional Title Here",
		"\" target=\"_blank",
		"\">",
		"an example",
		"</a>",
		" reference-style link.",
		"</p>\r\n",
		"<p>",
		"This is ",
		"<a href=\"http://example.com/",
		"\" title=\"Optional Title Here",
		"\" target=\"_blank",
		"\">",
		"an example",
		"</a>",
		" reference-style link.",
		"</p>\r\n",
		"<p>",
		"This is ",
		"<a href=\"http://example.com/",
		"\" title=\"Optional Title Here",
		"\" target=\"_blank",
		"\">",
		"an example",
		"</a>",
		" reference-style link.",
		"</p>\r\n",
		"<p>",
		"Visit ",
		"<a href=\"http://daringfireball.net/",
		"\" target=\"_blank",
		"\">",
		"Daring Fireball",
		"</a>",
		" for more information.",
		"</p>\r\n",
		"<p>",
		"I get 10 times more traffic from ",
		"<a href=\"http://google.com/",
		"\" title=\"Google",
		"\" target=\"_blank",
		"\">",
		"Google",
		"</a>",
		" than from ",
		"<a href=\"http://search.yahoo.com/",
		"\" title=\"Yahoo Search",
		"\" target=\"_blank",
		"\">",
		"Yahoo",
		"</a>",
		" or ",
		"<a href=\"http://search.msn.com/",
		"\" title=\"MSN Search",
		"\" target=\"_blank",
		"\">",
		"MSN",
		"</a>",
		".",
		"</p>\r\n",
		"<p>",
		"I get 10 times more traffic from ",
		"<a href=\"http://google.com/",
		"\" title=\"Google",
		"\" target=\"_blank",
		"\">",
		"Google",
		"</a>",
		" than from ",
		"<a href=\"http://search.yahoo.com/",
		"\" title=\"Yahoo Search",
		"\" target=\"_blank",
		"\">",
		"Yahoo",
		"</a>",
		" or ",
		"<a href=\"http://search.msn.com/",
		"\" title=\"MSN Search",
		"\" target=\"_blank",
		"\">",
		"MSN",
		"</a>",
		".",
		"</p>\r\n",
		"<p>",
		"I get 10 times more traffic from ",
		"<a href=\"http://google.com/",
		"\" title=\"Google",
		"\" target=\"_blank",
		"\">",
		"Google",
		"</a>",
		" than from ",
		"<a href=\"http://search.yahoo.com/",
		"\" title=\"Yahoo Search",
		"\" target=\"_blank",
		"\">",
		"Yahoo",
		"</a>",
		" or ",
		"<a href=\"http://search.msn.com/",
		"\" title=\"MSN Search",
		"\" target=\"_blank",
		"\">",
		"MSN",
		"</a>",
		".",
		"</p>\r\n",
		"<p>",
		"You can also write links, such as ",
		"<a href=\"http://lils.is/",
		"\" target=\"_blank",
		"\">http://lils.is/</a>",
		" inline.",
		"</p>\r\n",
		"<p>",
		"Or on separate paragraphs:",
		"</p>\r\n",
		"<p>",
		"<a href=\"http://lils.is/",
		"\" target=\"_blank",
		"\">http://lils.is/</a>",
		"</p>\r\n",
		"<p>",
		"Recognized multi-media content put on separate rows are automatically handled as multi-media:",
		"</p>\r\n",
		"<iframe src=\"https://www.youtube.com/embed/whBPLc8m4SU\">https://www.youtube.com/watch?v=whBPLc8m4SU</iframe>\r\n",
		"<p>",
		"<abbr data-title=\"is&nbsp;an&nbsp;abbreviation&nbsp;for&nbsp;abbreviation\">",
		"abbr",
		"</abbr>",
		".",
		"</p>\r\n"];
	return Segments.join("");
}
