function CreateInnerHTML(ElementId)
{
	var Element = document.getElementById(ElementId);
	if (Element)
		Element.innerHTML = CreateHTML();
}

function CreateHTML()
{
	var Segments = [
		"<p>",
		"<em>",
		"single asterisks",
		"</em>",
		"</p>\r\n",
		"<p>",
		"<u>",
		"single underscores",
		"</u>",
		"</p>\r\n",
		"<p>",
		"<s>",
		"single tildes",
		"</s>",
		"</p>\r\n",
		"<p>",
		"<strong>",
		"double asterisks",
		"</strong>",
		"</p>\r\n",
		"<p>",
		"<ins>",
		"double underscores",
		"</ins>",
		"</p>\r\n",
		"<p>",
		"<del>",
		"double tildes",
		"</del>",
		"</p>\r\n",
		"<p>",
		"un",
		"<em>",
		"frigging",
		"</em>",
		"believable",
		"</p>\r\n",
		"<p>",
		"This * will not be formatted, nor this * asterisk.",
		"</p>\r\n",
		"<p>",
		"This _ will not be formatted, nor this _ underscore.",
		"</p>\r\n",
		"<p>",
		"This ~ will not be formatted, nor this ~ tilde.",
		"</p>\r\n",
		"<p>",
		"*this text is surrounded by literal asterisks*",
		"</p>\r\n",
		"<p>",
		"Use the ",
		"<code>printf()</code>",
		" function.",
		"</p>\r\n",
		"<p>",
		"<code>There is a literal backtick (`) here.</code>",
		"</p>\r\n",
		"<p>",
		"A single backtick in a code span: ",
		"<code>`</code>",
		"</p>\r\n",
		"<p>",
		"A backtick-delimited string in a code span: ",
		"<code>`foo`</code>",
		"</p>\r\n",
		"<p>",
		"Please don",
		"&rsquo;",
		"t use any ",
		"<code>&lt;blink&gt;</code>",
		" tags.",
		"</p>\r\n",
		"<p>",
		"<code>&amp;#8212;</code>",
		" is the decimal-encoded equivalent of ",
		"<code>&amp;mdash;</code>",
		".",
		"</p>\r\n",
		"<p>",
		"*literal asterisks*",
		"</p>\r\n"];
	return Segments.join("");
}
