function CreateInnerHTML(ElementId)
{
	var Element = document.getElementById(ElementId);
	if (Element)
		Element.innerHTML = CreateHTML();
}

function CreateHTML()
{
	var Segments = [
		"<table>\r\n",
		"<colgroup>\r\n",
		"<col style=\"text-align:center\"/>\r\n",
		"<col style=\"text-align:center\"/>\r\n",
		"</colgroup>\r\n",
		"<thead>\r\n",
		"<tr>\r\n",
		"<th style=\"text-align:center",
		"\">",
		"Smiley",
		"</th>\r\n",
		"<th style=\"text-align:center",
		"\">",
		"Emoji",
		"</th>\r\n",
		"</tr>\r\n",
		"</thead>\r\n",
		"<tbody>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":heavy black heart:\" title=\"heart\" width=\"24\" height=\"24\" src=\"/emoji1/2764.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":heavy black heart:\" title=\"heart\" width=\"24\" height=\"24\" src=\"/emoji1/2764.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":broken heart:\" title=\"broken_heart\" width=\"24\" height=\"24\" src=\"/emoji1/1f494.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":broken heart:\" title=\"broken_heart\" width=\"24\" height=\"24\" src=\"/emoji1/1f494.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face with tears of joy:\" title=\"joy\" width=\"24\" height=\"24\" src=\"/emoji1/1f602.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face with tears of joy:\" title=\"joy\" width=\"24\" height=\"24\" src=\"/emoji1/1f602.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face with tears of joy:\" title=\"joy\" width=\"24\" height=\"24\" src=\"/emoji1/1f602.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face with tears of joy:\" title=\"joy\" width=\"24\" height=\"24\" src=\"/emoji1/1f602.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with open mouth:\" title=\"smiley\" width=\"24\" height=\"24\" src=\"/emoji1/1f603.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with open mouth:\" title=\"smiley\" width=\"24\" height=\"24\" src=\"/emoji1/1f603.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with open mouth:\" title=\"smiley\" width=\"24\" height=\"24\" src=\"/emoji1/1f603.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with open mouth:\" title=\"smiley\" width=\"24\" height=\"24\" src=\"/emoji1/1f603.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with open mouth:\" title=\"smiley\" width=\"24\" height=\"24\" src=\"/emoji1/1f603.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with open mouth:\" title=\"smiley\" width=\"24\" height=\"24\" src=\"/emoji1/1f603.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with open mouth and smiling eyes:\" title=\"smile\" width=\"24\" height=\"24\" src=\"/emoji1/1f604.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with open mouth and smiling eyes:\" title=\"smile\" width=\"24\" height=\"24\" src=\"/emoji1/1f604.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with open mouth and smiling eyes:\" title=\"smile\" width=\"24\" height=\"24\" src=\"/emoji1/1f604.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with open mouth and smiling eyes:\" title=\"smile\" width=\"24\" height=\"24\" src=\"/emoji1/1f604.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with open mouth and smiling eyes:\" title=\"smile\" width=\"24\" height=\"24\" src=\"/emoji1/1f604.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with open mouth and smiling eyes:\" title=\"smile\" width=\"24\" height=\"24\" src=\"/emoji1/1f604.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with open mouth and smiling eyes:\" title=\"smile\" width=\"24\" height=\"24\" src=\"/emoji1/1f604.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with open mouth and smiling eyes:\" title=\"smile\" width=\"24\" height=\"24\" src=\"/emoji1/1f604.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with open mouth and smiling eyes:\" title=\"smile\" width=\"24\" height=\"24\" src=\"/emoji1/1f604.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with open mouth and smiling eyes:\" title=\"smile\" width=\"24\" height=\"24\" src=\"/emoji1/1f604.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with open mouth and cold sweat:\" title=\"sweat_smile\" width=\"24\" height=\"24\" src=\"/emoji1/1f605.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with open mouth and cold sweat:\" title=\"sweat_smile\" width=\"24\" height=\"24\" src=\"/emoji1/1f605.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with open mouth and cold sweat:\" title=\"sweat_smile\" width=\"24\" height=\"24\" src=\"/emoji1/1f605.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with open mouth and cold sweat:\" title=\"sweat_smile\" width=\"24\" height=\"24\" src=\"/emoji1/1f605.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with open mouth and cold sweat:\" title=\"sweat_smile\" width=\"24\" height=\"24\" src=\"/emoji1/1f605.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with open mouth and cold sweat:\" title=\"sweat_smile\" width=\"24\" height=\"24\" src=\"/emoji1/1f605.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with open mouth and cold sweat:\" title=\"sweat_smile\" width=\"24\" height=\"24\" src=\"/emoji1/1f605.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with open mouth and cold sweat:\" title=\"sweat_smile\" width=\"24\" height=\"24\" src=\"/emoji1/1f605.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with open mouth and cold sweat:\" title=\"sweat_smile\" width=\"24\" height=\"24\" src=\"/emoji1/1f605.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with open mouth and cold sweat:\" title=\"sweat_smile\" width=\"24\" height=\"24\" src=\"/emoji1/1f605.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with open mouth and cold sweat:\" title=\"sweat_smile\" width=\"24\" height=\"24\" src=\"/emoji1/1f605.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with open mouth and cold sweat:\" title=\"sweat_smile\" width=\"24\" height=\"24\" src=\"/emoji1/1f605.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with open mouth and tightly-closed eyes:\" title=\"laughing\" width=\"24\" height=\"24\" src=\"/emoji1/1f606.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with open mouth and tightly-closed eyes:\" title=\"laughing\" width=\"24\" height=\"24\" src=\"/emoji1/1f606.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with open mouth and tightly-closed eyes:\" title=\"laughing\" width=\"24\" height=\"24\" src=\"/emoji1/1f606.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with open mouth and tightly-closed eyes:\" title=\"laughing\" width=\"24\" height=\"24\" src=\"/emoji1/1f606.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with open mouth and tightly-closed eyes:\" title=\"laughing\" width=\"24\" height=\"24\" src=\"/emoji1/1f606.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with open mouth and tightly-closed eyes:\" title=\"laughing\" width=\"24\" height=\"24\" src=\"/emoji1/1f606.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with open mouth and tightly-closed eyes:\" title=\"laughing\" width=\"24\" height=\"24\" src=\"/emoji1/1f606.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with open mouth and tightly-closed eyes:\" title=\"laughing\" width=\"24\" height=\"24\" src=\"/emoji1/1f606.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":winking face:\" title=\"wink\" width=\"24\" height=\"24\" src=\"/emoji1/1f609.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":winking face:\" title=\"wink\" width=\"24\" height=\"24\" src=\"/emoji1/1f609.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":winking face:\" title=\"wink\" width=\"24\" height=\"24\" src=\"/emoji1/1f609.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":winking face:\" title=\"wink\" width=\"24\" height=\"24\" src=\"/emoji1/1f609.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":winking face:\" title=\"wink\" width=\"24\" height=\"24\" src=\"/emoji1/1f609.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":winking face:\" title=\"wink\" width=\"24\" height=\"24\" src=\"/emoji1/1f609.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":winking face:\" title=\"wink\" width=\"24\" height=\"24\" src=\"/emoji1/1f609.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":winking face:\" title=\"wink\" width=\"24\" height=\"24\" src=\"/emoji1/1f609.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":winking face:\" title=\"wink\" width=\"24\" height=\"24\" src=\"/emoji1/1f609.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":winking face:\" title=\"wink\" width=\"24\" height=\"24\" src=\"/emoji1/1f609.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":winking face:\" title=\"wink\" width=\"24\" height=\"24\" src=\"/emoji1/1f609.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":winking face:\" title=\"wink\" width=\"24\" height=\"24\" src=\"/emoji1/1f609.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":winking face:\" title=\"wink\" width=\"24\" height=\"24\" src=\"/emoji1/1f609.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":winking face:\" title=\"wink\" width=\"24\" height=\"24\" src=\"/emoji1/1f609.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":winking face:\" title=\"wink\" width=\"24\" height=\"24\" src=\"/emoji1/1f609.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":winking face:\" title=\"wink\" width=\"24\" height=\"24\" src=\"/emoji1/1f609.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face with cold sweat:\" title=\"sweat\" width=\"24\" height=\"24\" src=\"/emoji1/1f613.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face with cold sweat:\" title=\"sweat\" width=\"24\" height=\"24\" src=\"/emoji1/1f613.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face with cold sweat:\" title=\"sweat\" width=\"24\" height=\"24\" src=\"/emoji1/1f613.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face with cold sweat:\" title=\"sweat\" width=\"24\" height=\"24\" src=\"/emoji1/1f613.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face with cold sweat:\" title=\"sweat\" width=\"24\" height=\"24\" src=\"/emoji1/1f613.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face with cold sweat:\" title=\"sweat\" width=\"24\" height=\"24\" src=\"/emoji1/1f613.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face throwing a kiss:\" title=\"kissing_heart\" width=\"24\" height=\"24\" src=\"/emoji1/1f618.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face throwing a kiss:\" title=\"kissing_heart\" width=\"24\" height=\"24\" src=\"/emoji1/1f618.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face throwing a kiss:\" title=\"kissing_heart\" width=\"24\" height=\"24\" src=\"/emoji1/1f618.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face throwing a kiss:\" title=\"kissing_heart\" width=\"24\" height=\"24\" src=\"/emoji1/1f618.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face throwing a kiss:\" title=\"kissing_heart\" width=\"24\" height=\"24\" src=\"/emoji1/1f618.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face throwing a kiss:\" title=\"kissing_heart\" width=\"24\" height=\"24\" src=\"/emoji1/1f618.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face throwing a kiss:\" title=\"kissing_heart\" width=\"24\" height=\"24\" src=\"/emoji1/1f618.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face throwing a kiss:\" title=\"kissing_heart\" width=\"24\" height=\"24\" src=\"/emoji1/1f618.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face with stuck-out tongue and winking eye:\" title=\"stuck_out_tongue_winking_eye\" width=\"24\" height=\"24\" src=\"/emoji1/1f61c.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face with stuck-out tongue and winking eye:\" title=\"stuck_out_tongue_winking_eye\" width=\"24\" height=\"24\" src=\"/emoji1/1f61c.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face with stuck-out tongue and winking eye:\" title=\"stuck_out_tongue_winking_eye\" width=\"24\" height=\"24\" src=\"/emoji1/1f61c.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face with stuck-out tongue and winking eye:\" title=\"stuck_out_tongue_winking_eye\" width=\"24\" height=\"24\" src=\"/emoji1/1f61c.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face with stuck-out tongue and winking eye:\" title=\"stuck_out_tongue_winking_eye\" width=\"24\" height=\"24\" src=\"/emoji1/1f61c.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face with stuck-out tongue and winking eye:\" title=\"stuck_out_tongue_winking_eye\" width=\"24\" height=\"24\" src=\"/emoji1/1f61c.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":disappointed face:\" title=\"disappointed\" width=\"24\" height=\"24\" src=\"/emoji1/1f61e.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":disappointed face:\" title=\"disappointed\" width=\"24\" height=\"24\" src=\"/emoji1/1f61e.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":disappointed face:\" title=\"disappointed\" width=\"24\" height=\"24\" src=\"/emoji1/1f61e.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":disappointed face:\" title=\"disappointed\" width=\"24\" height=\"24\" src=\"/emoji1/1f61e.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":disappointed face:\" title=\"disappointed\" width=\"24\" height=\"24\" src=\"/emoji1/1f61e.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":disappointed face:\" title=\"disappointed\" width=\"24\" height=\"24\" src=\"/emoji1/1f61e.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":disappointed face:\" title=\"disappointed\" width=\"24\" height=\"24\" src=\"/emoji1/1f61e.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":disappointed face:\" title=\"disappointed\" width=\"24\" height=\"24\" src=\"/emoji1/1f61e.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":disappointed face:\" title=\"disappointed\" width=\"24\" height=\"24\" src=\"/emoji1/1f61e.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":disappointed face:\" title=\"disappointed\" width=\"24\" height=\"24\" src=\"/emoji1/1f61e.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":disappointed face:\" title=\"disappointed\" width=\"24\" height=\"24\" src=\"/emoji1/1f61e.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":disappointed face:\" title=\"disappointed\" width=\"24\" height=\"24\" src=\"/emoji1/1f61e.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":angry face:\" title=\"angry\" width=\"24\" height=\"24\" src=\"/emoji1/1f620.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":angry face:\" title=\"angry\" width=\"24\" height=\"24\" src=\"/emoji1/1f620.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":angry face:\" title=\"angry\" width=\"24\" height=\"24\" src=\"/emoji1/1f620.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":angry face:\" title=\"angry\" width=\"24\" height=\"24\" src=\"/emoji1/1f620.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":angry face:\" title=\"angry\" width=\"24\" height=\"24\" src=\"/emoji1/1f620.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":angry face:\" title=\"angry\" width=\"24\" height=\"24\" src=\"/emoji1/1f620.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":crying face:\" title=\"cry\" width=\"24\" height=\"24\" src=\"/emoji1/1f622.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":crying face:\" title=\"cry\" width=\"24\" height=\"24\" src=\"/emoji1/1f622.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":crying face:\" title=\"cry\" width=\"24\" height=\"24\" src=\"/emoji1/1f622.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":crying face:\" title=\"cry\" width=\"24\" height=\"24\" src=\"/emoji1/1f622.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":crying face:\" title=\"cry\" width=\"24\" height=\"24\" src=\"/emoji1/1f622.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":crying face:\" title=\"cry\" width=\"24\" height=\"24\" src=\"/emoji1/1f622.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":crying face:\" title=\"cry\" width=\"24\" height=\"24\" src=\"/emoji1/1f622.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":crying face:\" title=\"cry\" width=\"24\" height=\"24\" src=\"/emoji1/1f622.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":persevering face:\" title=\"persevere\" width=\"24\" height=\"24\" src=\"/emoji1/1f623.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":persevering face:\" title=\"persevere\" width=\"24\" height=\"24\" src=\"/emoji1/1f623.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":flushed face:\" title=\"flushed\" width=\"24\" height=\"24\" src=\"/emoji1/1f633.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":flushed face:\" title=\"flushed\" width=\"24\" height=\"24\" src=\"/emoji1/1f633.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":flushed face:\" title=\"flushed\" width=\"24\" height=\"24\" src=\"/emoji1/1f633.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":flushed face:\" title=\"flushed\" width=\"24\" height=\"24\" src=\"/emoji1/1f633.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":dizzy face:\" title=\"dizzy_face\" width=\"24\" height=\"24\" src=\"/emoji1/1f635.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":dizzy face:\" title=\"dizzy_face\" width=\"24\" height=\"24\" src=\"/emoji1/1f635.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":dizzy face:\" title=\"dizzy_face\" width=\"24\" height=\"24\" src=\"/emoji1/1f635.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":dizzy face:\" title=\"dizzy_face\" width=\"24\" height=\"24\" src=\"/emoji1/1f635.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":dizzy face:\" title=\"dizzy_face\" width=\"24\" height=\"24\" src=\"/emoji1/1f635.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":dizzy face:\" title=\"dizzy_face\" width=\"24\" height=\"24\" src=\"/emoji1/1f635.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":dizzy face:\" title=\"dizzy_face\" width=\"24\" height=\"24\" src=\"/emoji1/1f635.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":dizzy face:\" title=\"dizzy_face\" width=\"24\" height=\"24\" src=\"/emoji1/1f635.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":dizzy face:\" title=\"dizzy_face\" width=\"24\" height=\"24\" src=\"/emoji1/1f635.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":dizzy face:\" title=\"dizzy_face\" width=\"24\" height=\"24\" src=\"/emoji1/1f635.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":dizzy face:\" title=\"dizzy_face\" width=\"24\" height=\"24\" src=\"/emoji1/1f635.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":dizzy face:\" title=\"dizzy_face\" width=\"24\" height=\"24\" src=\"/emoji1/1f635.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face with ok gesture:\" title=\"ok_woman\" width=\"24\" height=\"24\" src=\"/emoji1/1f646.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face with ok gesture:\" title=\"ok_woman\" width=\"24\" height=\"24\" src=\"/emoji1/1f646.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face with ok gesture:\" title=\"ok_woman\" width=\"24\" height=\"24\" src=\"/emoji1/1f646.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face with ok gesture:\" title=\"ok_woman\" width=\"24\" height=\"24\" src=\"/emoji1/1f646.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face with ok gesture:\" title=\"ok_woman\" width=\"24\" height=\"24\" src=\"/emoji1/1f646.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face with ok gesture:\" title=\"ok_woman\" width=\"24\" height=\"24\" src=\"/emoji1/1f646.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face with ok gesture:\" title=\"ok_woman\" width=\"24\" height=\"24\" src=\"/emoji1/1f646.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face with ok gesture:\" title=\"ok_woman\" width=\"24\" height=\"24\" src=\"/emoji1/1f646.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with halo:\" title=\"innocent\" width=\"24\" height=\"24\" src=\"/emoji1/1f607.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with halo:\" title=\"innocent\" width=\"24\" height=\"24\" src=\"/emoji1/1f607.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with halo:\" title=\"innocent\" width=\"24\" height=\"24\" src=\"/emoji1/1f607.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with halo:\" title=\"innocent\" width=\"24\" height=\"24\" src=\"/emoji1/1f607.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with halo:\" title=\"innocent\" width=\"24\" height=\"24\" src=\"/emoji1/1f607.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with halo:\" title=\"innocent\" width=\"24\" height=\"24\" src=\"/emoji1/1f607.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with halo:\" title=\"innocent\" width=\"24\" height=\"24\" src=\"/emoji1/1f607.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with halo:\" title=\"innocent\" width=\"24\" height=\"24\" src=\"/emoji1/1f607.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with halo:\" title=\"innocent\" width=\"24\" height=\"24\" src=\"/emoji1/1f607.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with halo:\" title=\"innocent\" width=\"24\" height=\"24\" src=\"/emoji1/1f607.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with halo:\" title=\"innocent\" width=\"24\" height=\"24\" src=\"/emoji1/1f607.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with halo:\" title=\"innocent\" width=\"24\" height=\"24\" src=\"/emoji1/1f607.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with halo:\" title=\"innocent\" width=\"24\" height=\"24\" src=\"/emoji1/1f607.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with halo:\" title=\"innocent\" width=\"24\" height=\"24\" src=\"/emoji1/1f607.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with halo:\" title=\"innocent\" width=\"24\" height=\"24\" src=\"/emoji1/1f607.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with halo:\" title=\"innocent\" width=\"24\" height=\"24\" src=\"/emoji1/1f607.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with halo:\" title=\"innocent\" width=\"24\" height=\"24\" src=\"/emoji1/1f607.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with halo:\" title=\"innocent\" width=\"24\" height=\"24\" src=\"/emoji1/1f607.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with halo:\" title=\"innocent\" width=\"24\" height=\"24\" src=\"/emoji1/1f607.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with halo:\" title=\"innocent\" width=\"24\" height=\"24\" src=\"/emoji1/1f607.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with halo:\" title=\"innocent\" width=\"24\" height=\"24\" src=\"/emoji1/1f607.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with halo:\" title=\"innocent\" width=\"24\" height=\"24\" src=\"/emoji1/1f607.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with halo:\" title=\"innocent\" width=\"24\" height=\"24\" src=\"/emoji1/1f607.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with halo:\" title=\"innocent\" width=\"24\" height=\"24\" src=\"/emoji1/1f607.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with halo:\" title=\"innocent\" width=\"24\" height=\"24\" src=\"/emoji1/1f607.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with halo:\" title=\"innocent\" width=\"24\" height=\"24\" src=\"/emoji1/1f607.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with sunglasses:\" title=\"sunglasses\" width=\"24\" height=\"24\" src=\"/emoji1/1f60e.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with sunglasses:\" title=\"sunglasses\" width=\"24\" height=\"24\" src=\"/emoji1/1f60e.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with sunglasses:\" title=\"sunglasses\" width=\"24\" height=\"24\" src=\"/emoji1/1f60e.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with sunglasses:\" title=\"sunglasses\" width=\"24\" height=\"24\" src=\"/emoji1/1f60e.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with sunglasses:\" title=\"sunglasses\" width=\"24\" height=\"24\" src=\"/emoji1/1f60e.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with sunglasses:\" title=\"sunglasses\" width=\"24\" height=\"24\" src=\"/emoji1/1f60e.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with sunglasses:\" title=\"sunglasses\" width=\"24\" height=\"24\" src=\"/emoji1/1f60e.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with sunglasses:\" title=\"sunglasses\" width=\"24\" height=\"24\" src=\"/emoji1/1f60e.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with sunglasses:\" title=\"sunglasses\" width=\"24\" height=\"24\" src=\"/emoji1/1f60e.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with sunglasses:\" title=\"sunglasses\" width=\"24\" height=\"24\" src=\"/emoji1/1f60e.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with sunglasses:\" title=\"sunglasses\" width=\"24\" height=\"24\" src=\"/emoji1/1f60e.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":smiling face with sunglasses:\" title=\"sunglasses\" width=\"24\" height=\"24\" src=\"/emoji1/1f60e.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":expressionless face:\" title=\"expressionless\" width=\"24\" height=\"24\" src=\"/emoji1/1f611.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":expressionless face:\" title=\"expressionless\" width=\"24\" height=\"24\" src=\"/emoji1/1f611.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":expressionless face:\" title=\"expressionless\" width=\"24\" height=\"24\" src=\"/emoji1/1f611.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":expressionless face:\" title=\"expressionless\" width=\"24\" height=\"24\" src=\"/emoji1/1f611.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":expressionless face:\" title=\"expressionless\" width=\"24\" height=\"24\" src=\"/emoji1/1f611.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":expressionless face:\" title=\"expressionless\" width=\"24\" height=\"24\" src=\"/emoji1/1f611.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":confused face:\" title=\"confused\" width=\"24\" height=\"24\" src=\"/emoji1/1f615.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":confused face:\" title=\"confused\" width=\"24\" height=\"24\" src=\"/emoji1/1f615.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":confused face:\" title=\"confused\" width=\"24\" height=\"24\" src=\"/emoji1/1f615.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":confused face:\" title=\"confused\" width=\"24\" height=\"24\" src=\"/emoji1/1f615.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":confused face:\" title=\"confused\" width=\"24\" height=\"24\" src=\"/emoji1/1f615.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":confused face:\" title=\"confused\" width=\"24\" height=\"24\" src=\"/emoji1/1f615.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":confused face:\" title=\"confused\" width=\"24\" height=\"24\" src=\"/emoji1/1f615.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":confused face:\" title=\"confused\" width=\"24\" height=\"24\" src=\"/emoji1/1f615.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":confused face:\" title=\"confused\" width=\"24\" height=\"24\" src=\"/emoji1/1f615.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":confused face:\" title=\"confused\" width=\"24\" height=\"24\" src=\"/emoji1/1f615.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":confused face:\" title=\"confused\" width=\"24\" height=\"24\" src=\"/emoji1/1f615.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":confused face:\" title=\"confused\" width=\"24\" height=\"24\" src=\"/emoji1/1f615.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":confused face:\" title=\"confused\" width=\"24\" height=\"24\" src=\"/emoji1/1f615.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":confused face:\" title=\"confused\" width=\"24\" height=\"24\" src=\"/emoji1/1f615.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":confused face:\" title=\"confused\" width=\"24\" height=\"24\" src=\"/emoji1/1f615.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":confused face:\" title=\"confused\" width=\"24\" height=\"24\" src=\"/emoji1/1f615.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":confused face:\" title=\"confused\" width=\"24\" height=\"24\" src=\"/emoji1/1f615.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":confused face:\" title=\"confused\" width=\"24\" height=\"24\" src=\"/emoji1/1f615.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":confused face:\" title=\"confused\" width=\"24\" height=\"24\" src=\"/emoji1/1f615.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":confused face:\" title=\"confused\" width=\"24\" height=\"24\" src=\"/emoji1/1f615.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face with stuck-out tongue:\" title=\"stuck_out_tongue\" width=\"24\" height=\"24\" src=\"/emoji1/1f61b.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face with stuck-out tongue:\" title=\"stuck_out_tongue\" width=\"24\" height=\"24\" src=\"/emoji1/1f61b.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face with stuck-out tongue:\" title=\"stuck_out_tongue\" width=\"24\" height=\"24\" src=\"/emoji1/1f61b.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face with stuck-out tongue:\" title=\"stuck_out_tongue\" width=\"24\" height=\"24\" src=\"/emoji1/1f61b.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face with stuck-out tongue:\" title=\"stuck_out_tongue\" width=\"24\" height=\"24\" src=\"/emoji1/1f61b.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face with stuck-out tongue:\" title=\"stuck_out_tongue\" width=\"24\" height=\"24\" src=\"/emoji1/1f61b.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face with stuck-out tongue:\" title=\"stuck_out_tongue\" width=\"24\" height=\"24\" src=\"/emoji1/1f61b.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face with stuck-out tongue:\" title=\"stuck_out_tongue\" width=\"24\" height=\"24\" src=\"/emoji1/1f61b.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face with stuck-out tongue:\" title=\"stuck_out_tongue\" width=\"24\" height=\"24\" src=\"/emoji1/1f61b.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face with stuck-out tongue:\" title=\"stuck_out_tongue\" width=\"24\" height=\"24\" src=\"/emoji1/1f61b.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face with stuck-out tongue:\" title=\"stuck_out_tongue\" width=\"24\" height=\"24\" src=\"/emoji1/1f61b.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face with stuck-out tongue:\" title=\"stuck_out_tongue\" width=\"24\" height=\"24\" src=\"/emoji1/1f61b.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face with stuck-out tongue:\" title=\"stuck_out_tongue\" width=\"24\" height=\"24\" src=\"/emoji1/1f61b.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face with stuck-out tongue:\" title=\"stuck_out_tongue\" width=\"24\" height=\"24\" src=\"/emoji1/1f61b.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face with stuck-out tongue:\" title=\"stuck_out_tongue\" width=\"24\" height=\"24\" src=\"/emoji1/1f61b.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face with stuck-out tongue:\" title=\"stuck_out_tongue\" width=\"24\" height=\"24\" src=\"/emoji1/1f61b.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face with stuck-out tongue:\" title=\"stuck_out_tongue\" width=\"24\" height=\"24\" src=\"/emoji1/1f61b.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face with stuck-out tongue:\" title=\"stuck_out_tongue\" width=\"24\" height=\"24\" src=\"/emoji1/1f61b.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face with stuck-out tongue:\" title=\"stuck_out_tongue\" width=\"24\" height=\"24\" src=\"/emoji1/1f61b.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face with stuck-out tongue:\" title=\"stuck_out_tongue\" width=\"24\" height=\"24\" src=\"/emoji1/1f61b.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face with stuck-out tongue:\" title=\"stuck_out_tongue\" width=\"24\" height=\"24\" src=\"/emoji1/1f61b.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face with stuck-out tongue:\" title=\"stuck_out_tongue\" width=\"24\" height=\"24\" src=\"/emoji1/1f61b.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face with stuck-out tongue:\" title=\"stuck_out_tongue\" width=\"24\" height=\"24\" src=\"/emoji1/1f61b.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face with stuck-out tongue:\" title=\"stuck_out_tongue\" width=\"24\" height=\"24\" src=\"/emoji1/1f61b.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face with stuck-out tongue:\" title=\"stuck_out_tongue\" width=\"24\" height=\"24\" src=\"/emoji1/1f61b.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face with stuck-out tongue:\" title=\"stuck_out_tongue\" width=\"24\" height=\"24\" src=\"/emoji1/1f61b.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face with open mouth:\" title=\"open_mouth\" width=\"24\" height=\"24\" src=\"/emoji1/1f62e.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face with open mouth:\" title=\"open_mouth\" width=\"24\" height=\"24\" src=\"/emoji1/1f62e.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face with open mouth:\" title=\"open_mouth\" width=\"24\" height=\"24\" src=\"/emoji1/1f62e.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face with open mouth:\" title=\"open_mouth\" width=\"24\" height=\"24\" src=\"/emoji1/1f62e.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face with open mouth:\" title=\"open_mouth\" width=\"24\" height=\"24\" src=\"/emoji1/1f62e.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face with open mouth:\" title=\"open_mouth\" width=\"24\" height=\"24\" src=\"/emoji1/1f62e.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face with open mouth:\" title=\"open_mouth\" width=\"24\" height=\"24\" src=\"/emoji1/1f62e.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face with open mouth:\" title=\"open_mouth\" width=\"24\" height=\"24\" src=\"/emoji1/1f62e.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face with open mouth:\" title=\"open_mouth\" width=\"24\" height=\"24\" src=\"/emoji1/1f62e.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face with open mouth:\" title=\"open_mouth\" width=\"24\" height=\"24\" src=\"/emoji1/1f62e.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face with open mouth:\" title=\"open_mouth\" width=\"24\" height=\"24\" src=\"/emoji1/1f62e.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face with open mouth:\" title=\"open_mouth\" width=\"24\" height=\"24\" src=\"/emoji1/1f62e.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face without mouth:\" title=\"no_mouth\" width=\"24\" height=\"24\" src=\"/emoji1/1f636.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face without mouth:\" title=\"no_mouth\" width=\"24\" height=\"24\" src=\"/emoji1/1f636.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face without mouth:\" title=\"no_mouth\" width=\"24\" height=\"24\" src=\"/emoji1/1f636.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face without mouth:\" title=\"no_mouth\" width=\"24\" height=\"24\" src=\"/emoji1/1f636.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face without mouth:\" title=\"no_mouth\" width=\"24\" height=\"24\" src=\"/emoji1/1f636.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face without mouth:\" title=\"no_mouth\" width=\"24\" height=\"24\" src=\"/emoji1/1f636.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face without mouth:\" title=\"no_mouth\" width=\"24\" height=\"24\" src=\"/emoji1/1f636.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face without mouth:\" title=\"no_mouth\" width=\"24\" height=\"24\" src=\"/emoji1/1f636.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face without mouth:\" title=\"no_mouth\" width=\"24\" height=\"24\" src=\"/emoji1/1f636.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face without mouth:\" title=\"no_mouth\" width=\"24\" height=\"24\" src=\"/emoji1/1f636.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face without mouth:\" title=\"no_mouth\" width=\"24\" height=\"24\" src=\"/emoji1/1f636.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face without mouth:\" title=\"no_mouth\" width=\"24\" height=\"24\" src=\"/emoji1/1f636.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face without mouth:\" title=\"no_mouth\" width=\"24\" height=\"24\" src=\"/emoji1/1f636.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face without mouth:\" title=\"no_mouth\" width=\"24\" height=\"24\" src=\"/emoji1/1f636.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face without mouth:\" title=\"no_mouth\" width=\"24\" height=\"24\" src=\"/emoji1/1f636.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face without mouth:\" title=\"no_mouth\" width=\"24\" height=\"24\" src=\"/emoji1/1f636.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"<tr>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face without mouth:\" title=\"no_mouth\" width=\"24\" height=\"24\" src=\"/emoji1/1f636.svg\"/>",
		"</td>\r\n",
		"<td style=\"text-align:center",
		"\">",
		"<img alt=\":face without mouth:\" title=\"no_mouth\" width=\"24\" height=\"24\" src=\"/emoji1/1f636.svg\"/>",
		"</td>\r\n",
		"</tr>\r\n",
		"</tbody>\r\n",
		"</table>\r\n"];
	return Segments.join("");
}
